### ISSUE TITLE
Siren on Ring spotlight cam (battery)

### ISSUE THREAD

**Issue by beklever** [tchellomello/python-ring-doorbell#103]
Hi there,
I cannot get the siren to work on the spotlight cam. If I use the siren like in the scripts for the floodlight, everything stays silent.
When I use the lights however, the lights turn on. Is there something different between the floodlight and spotlight camera's?

Thanks for any help, love your work!

**Comment by tchellomello** [comment]
Hello @beklever, 
   Thanks for your kind words. Unfortunately, I don't have the spotlight, but some other users might be able to provide you some assistance.

**Comment by dgreif** [comment]
After messing around with this for the node Ring client, I came to the conclusion the the siren endpoint behaves differently for battery vs wired cameras.  For wired cameras (like the floodlight cam), you can turn the siren on/off at any time.  For battery cameras, the endpoint only works when the camera is _currently live streaming_.  I think the idea is that you are always watching a live stream when you want to turn the siren on/off.  Makes sense in theory, but sucks if you want to automate the siren of a battery cam based on some other sensors.  Unfortunately this is a Ring issue and not something that can be fixed from the client end.

**Comment by Sku1ly** [comment]
I know this is old but my battery powered spotlight and new battery powered stick up cam are now both activating siren in home assistant
