### ISSUE TITLE
How can I connect to the SIP Session

### ISSUE THREAD

**Issue by nemr-maher** [tchellomello/python-ring-doorbell#105]
Thanks for this great module.

How can I connect to the SIP session with the provided SIP details?

**Comment by tchellomello** [comment]
Hello @nemr-maher, 

Thanks for your kind words. 

Ring.com don't offer a public API and all the contributors in this project have tried to implement a hack to connect with the SIP session without very much success.  

You can see more details at https://github.com/tchellomello/python-ring-doorbell/issues/23 and please feel free to add any contributions or information you might find to get this working. 

I'm closing this issue in as we can centralized the discussion at  #23 

Thank you!
