### ISSUE TITLE
Feature Request: Add a model property to identify the different products

### ISSUE THREAD

**Issue by jsetton** [tchellomello/python-ring-doorbell#112]
With all the new products that Ring has added in the last year, it would be nice if we could catalog them and add some logic to identify their model. This is especially a need for the `stickup_cam` family umbrella and their different power source. For example, the `battery_life` property on a Floodlight cam is returning some value while that product is AC powered only and no other device property seems to identify the power source properly.

Here is all the information I was able to gather from the APK. I used the same model names listed in the application package. Some of the models use a combination of the `kind` and `ring_cam_setup_flow` properties.

| Model | Family | Power | `kind` | `ring_cam_setup_flow` |
| --- | --- | --- | --- | --- |
| Chime | chimes | hardwired | `chime` | |
| Chime Pro | chimes | hardwired | `chime_pro` | |
| Doorbell | doorbots | battery | `doorbot`<br>`doorbell`<br>`doorbell_v3` | |
| Doorbell 2 | doorbots | battery | `doorbell_v4`<br>`doorbell_v5` | |
| Doorbell Pro | doorbots | hardwired | `lpd_v1`<br>`lpd_v2` | |
| Doorbell Elite | doorbots | hardwired | `jbox_v1` | |
| Floodlight Cam | stickup_cam | hardwired | `hp_cam_v1` | `floodlight` |
| Spotlight Cam Battery | stickup_cam | battery | `stickup_cam_v4` | (`battery`) |
| Spotlight Cam Mount | stickup_cam | hardwired | `hp_cam_v2` | `mount` |
| Spotlight Cam Solar | stickup_cam | battery | `stickup_cam_v4` | `solar` |
| Spotlight Cam Wired | stickup_cam | hardwired | `hp_cam_v2` | (`wired`) |
| Stick Up Cam | stickup_cam | battery | `stickup_cam`<br>`stickup_cam_v3` | |
| Stick Up Cam Battery | stickup_cam | battery | `stickup_cam_lunar` | |
| Stick Up Cam Wired | stickup_cam | hardwired | `stickup_cam_elite` | |

Capabilities:

| Model | Battery | Light | Siren | Volume |
| --- | :---: | :---: | :---: | :---: |
| Chime | :x: | :x: | :x: | :heavy_check_mark: |
| Chime Pro | :x: | :x: | :x: | :heavy_check_mark: |
| Doorbell | :heavy_check_mark: | :x: | :x: | :heavy_check_mark: |
| Doorbell 2 | :heavy_check_mark: | :x: | :x: | :heavy_check_mark: |
| Doorbell Pro | :x: | :x: | :x: | :heavy_check_mark: |
| Doorbell Elite | :x: | :x: | :x: | :heavy_check_mark: |
| Floodlight Cam | :x: | :heavy_check_mark: | :heavy_check_mark: | :x: |
| Spotlight Cam Battery | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: |
| Spotlight Cam Mount | :x: | :heavy_check_mark: | :heavy_check_mark: | :x: |
| Spotlight Cam Solar | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: |
| Spotlight Cam Wired | :x: | :heavy_check_mark: | :heavy_check_mark: | :x: |
| Stick Up Cam | :heavy_check_mark: | :x: | :x: | :x: |
| Stick Up Cam Battery | :heavy_check_mark: | :x: | :heavy_check_mark: | :x: |
| Stick Up Cam Wired | :x: | :x: | :heavy_check_mark: | :x: |

**Comment by jsetton** [comment]
@evanjd @steveww I noticed you submitted PRs recently relevant to some of the devices I am missing data above. Any chance you could provide that information? I think with your input I would be able to determine if this feature can be implemented or not. Thanks.

**Comment by evanjd** [comment]
My Spotlight Cam battery's kind value is `stickup_cam_v4`. Where did you get the `ring_cam_setup_flow` prop from?

I wonder if we can extract these values from the official apps...

**Comment by jsetton** [comment]
Thanks for your input. The `ring_cam_setup_flow` property should appear in the device object response at least it shows under my floodlight cam. Maybe there is another property on your end that might identify your device as a spotlight cam. If not, I guess looking for the `led_status` property would allow to differentiate a spotlight cam from stickup cam. In regards to the power source, I would need confirmation but it seems that the `battery_life` property may be sufficient, on these devices, to differentiate between battery and hardwired.

```
{
  "doorbots": [],
  "authorized_doorbots": [],
  "chimes": [],
  "stickup_cams": [
    {
[...]
      "kind": "hp_cam_v1",
[...]
      "ring_cam_setup_flow": "floodlight",
[...]
    }
  ],
  "base_stations": [],
  "beams_bridges": [],
  "beams": []
}
```

Good idea on the official app. I was able to find some of the keywords listed in table above in the android app apk files but it is hard to do the proper correlation without a couple more data inputs.

**Comment by evanjd** [comment]
I had a dig through the APK, I think the `kind` values for the remaining devices in your list are:

- Doorbell Pro: `lpd_v1`
- Doorbell Pro 2: `lpd_v2`
- Doorbell Elite: `jbox_v1`
- Stickup Cam v1: `stickup_cam_v3`
- Stickup Cam v2 wired: `stickup_cam_elite`
- Stickup Cam v2 wireless: `stickup_cam_lunar`

This roughly lines up with the images assigned to the CSS classes of the same names I pulled from their page: https://pastebin.com/zrP8K3We

Also, I think you've got the `doorbell_v1` and `doorbell_v2` wrong on your table. I think the `lpd` prefix is specific to pro doorbells. My 1st gen doorbell has a kind of `doorbell_v3`.

**Comment by evanjd** [comment]
Nice! I don't see the `ring_cam_setup_flow` prop set anywhere in my device's properties. If it helps, here's a dump of all my device properties (anonymized): https://pastebin.com/Z36jJ9a2

**Comment by jsetton** [comment]
Ok thanks for confirming. Although in the app code it seems that the `ring_cam_setup_flow` should be set for the Spotlight Cam Battery model, it is only checked against the other model (solar) to differentiate the two products part of `stickup_cam_v4`. Same behavior between the Spotlight Cam Mount and Wired models where only the mount one is checked for that property. So the implementation will have to follow that logic.

**Comment by tchellomello** [comment]
Guys, loved the idea!! The matrix of products since the first version of this library has changed a lot and having this would help a lot. @jsetton  are you looking to submit a PR for this?

**Comment by jsetton** [comment]
@tchellomello I am. You can assign this one to me. Working on other projects in parallel. So it is taking a little longer than I originally expected.

**Comment by jsetton** [comment]
@tchellomello I just submitted a PR based adding two properties; one for the model name and the second one to determine if the relevant model is wired-enabled.
