### ISSUE TITLE
check_alerts() on multiple doorbell devices

### ISSUE THREAD

**Issue by kevnflores** [tchellomello/python-ring-doorbell#118]
Hi, I'm running the following

```
back_door = myring.doorbells[0].check_alerts()
front_door = myring.doorbells[1].check_alerts()

print('BackDoor: ' + str(back_door))
print('FrontDoor: ' + str(front_door))
```
Whenever I trigger a ring on either device the results are different, so if I go and ring the front door I would get the following:
```
BackDoor: None
FrontDoor: True
```

when I ring the same doorbell and run it again I get the following:
```
BackDoor: True
FrontDoor: None
```

Is there a way to specify by Ring name as opposed to the array number? I'm not sure if anyone has worked with multi-device notifications?

**Comment by kevnflores** [comment]
After some digging, I revisited this error and found that the returned values are never the same, so if I specify an integer the values will be different every time. When I do a check alerts it will return a false/true statement for different doorbells.

```myring.doorbells
[<RingDoorBell: Front Door>, <RingDoorBell: Side Door>, <RingDoorBell: Back Door>]```

```myring.doorbells
[<RingDoorBell: Back Door>, <RingDoorBell: Front Door>, <RingDoorBell: Side Door>]```

is there a way to alphabetize these values or allow for for string queries? 

When I run this: 
```myring.doorbells['Back Door'].check_alerts```

I get the following error:

```  File "<stdin>", line 1, in <module>
TypeError: list indices must be integers or slices, not str```

Any help with this would be greatly appreciated.

**Comment by nuketownhf** [comment]
I am having the same problem!
Somebody got a fix for that issue?
