### ISSUE TITLE
Feature Request: Support the latest Feature 'Camera Preview'

### ISSUE THREAD

**Issue by DoctorIOT** [tchellomello/python-ring-doorbell#119]
Add the ability to retrieve a snapshot from the ring camera, this is not from a recorded video but live.

**Comment by eugeneniemand** [comment]
Another vote for this. I use home assistant and this would be a very useful feature.

**Comment by jsetton** [comment]
This feature has already been implemented and merged into the repository.

#108

**Comment by energee** [comment]
Doesn't work :(

**Comment by eugeneniemand** [comment]
>Doesn't work :(

@energee I’ve not tried this but do you mean the g feature does not work in home assistant or natively in this library?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by energee** [comment]
Snapshot method returns 401, will look into it and submit a patch
