### ISSUE TITLE
How to use this script python-ring-doorbell?

### ISSUE THREAD

**Issue by Doudy** [tchellomello/python-ring-doorbell#120]
_**So I installed as written at the beginning**_
`//install python
$ sudo apt-get install python-pip

//install ring api
pip install ring_doorbell

pip install git+https://github.com/tchellomello/python-ring-doorbell@master

//installé les lib python au cas où
sudo apt-get install -y python3
sudo apt-get install -y python3-dev
sudo apt-get install -y python3-pip
sudo apt-get install -y python-urllib2
sudo pip3 install request`

**_copy the archive into: / home / pi / domoticz / scripts / python_**

**_When i start_**
`python /home/pi/domoticz/scripts/python/python-ring-doorbell-master/ring_doorbell/__init__.py`
**_the PI gives me back my hand
Is there anything to do, I did not enter a bell IP_**

**_When I execute:_**
`python /home/pi/domoticz/scripts/python/python-ring-doorbell-master/scripts/ringcli.py`
**_he asks me for a username and password
I enter my login and password, then go back to the root without a message_**

**_When i do:_**
`pi@RASPBERRYPI-xxx:~/domoticz/scripts/python/python-ring-doorbell-master/scripts $ python ringcli.py --count`
**_I get :_**
```---------------------------------
Ring CLI
Username: xxxxxxxx
Password: xxxxxxxxx
---------------------------------
        Counting videos linked on your Ring account.
        This may take some time....

        Total videos: 507
        Ding triggered: 73
        Motion triggered: 428
        On-Demand triggered: 6
```
**_when I press the bell button again:_**
```
Total videos: 509
        Ding triggered: 75
        Motion triggered: 428
        On-Demand triggered: 6
```

**_So it works but what to do next?_**

**Comment by Doudy** [comment]
Nobody ?

**Comment by Doudy** [comment]
Hello,
How am I doing this "Initializing your Ring object"?

`Initializing your Ring object
from ring_doorbell import Ring
myring = Ring('foo@bar', 'secret')

myring.is_connected
True`

Help

**Comment by Doudy** [comment]
Hello,
How am I doing this "Initializing your Ring object"?

`Initializing your Ring object
from ring_doorbell import Ring
myring = Ring('foo@bar', 'secret')

myring.is_connected
True`

Help

**Comment by jendrush** [comment]
@Doudy Sorry for writing to you this way, but i do not see option for contact in interceptWH2600. Could you please repair links for installation instructions?

**Comment by Doudy** [comment]
I have the following adress
http://www.domoticz.com/forum/viewtopic.php?t=15278
http://www.domoticz.com/forum/viewtopic.php?t=13272
http://www.domoticz.com/forum/viewtopic.php?f=38&t=15278&start=40
https://github.com/Doudy/interceptWH2600

You have also : 
http://www.weewx.com/hardware.html
https://github.com/weewx/weewx/wiki/observer (not tested)
http://www.weewx.com/docs/usersguide.htm#Computer_hardware

**Comment by BillyCroan** [comment]
When I run :

> root@RingPi:~/gits/python-ring-doorbell# python scripts/ringcli.py 
I only get this error:

> Traceback (most recent call last):
>   File "/root/gits/python-ring-doorbell/scripts/ringcli.py", line 16, in <module>
>     from ring_doorbell.cli import cli
> ModuleNotFoundError: No module named 'ring_doorbell'
> root@RingPi:~/gits/python-ring-doorbell# python scripts/ringcli.py 
> Traceback (most recent call last):
>   File "/root/gits/python-ring-doorbell/scripts/ringcli.py", line 16, in <module>
>     from ring_doorbell.cli import cli
> ModuleNotFoundError: No module named 'ring_doorbell'
> root@RingPi:~/gits/python-ring-doorbell# 
>
