### ISSUE TITLE
Get video URL link faster

### ISSUE THREAD

**Issue by MantieReid** [tchellomello/python-ring-doorbell#136]
Is there a way to get  the video link  for the video faster?
I have a few hundred videos, and I retrieve the links for each of them by using 

```   python
      for x in eventidlist:
      adddownloadurl = doorbell.recording_url(x)
      downloasdurl.append(adddownloadurl)
      print(downloasdurl)
      print("download url number of items is now " + str(len(downloasdurl)) )
```
But it takes forever to get just one link. At least a good 15-30 seconds or more.  When I went straight to ring to get the video url, they gave it to me much more faster.   Is there a faster way to get the video url for each video?

**Comment by nuketownhf** [comment]
I don't get why such simple questions do not get any answers, I'd love to know it too...
