### ISSUE TITLE
Number of events accessible

### ISSUE THREAD

**Issue by ifuchs** [tchellomello/python-ring-doorbell#141]
I can list info for 100 past events using doorbell.history.  Is this a limit set by Ring? I had thought that they keep 30 days of events but my last 100 events only cover 4 days.

**Comment by thanneman79** [comment]
I'd be interested in this answer also. Do to an issue I didn't notice my utility the uses this library hasn't ran since 11/1

**Comment by mbelie** [comment]
Just tried this for the first time today and am seeing the same thing. History results seemed to be capped at 100 regardless of the limit specified. I tried with "enforce_limit" equal to True and calling history without any parameters. The size of the result set is 30 with the latter call. I can see in the Android Ring app that the history can be paged past 100 records.

**Comment by mbelie** [comment]
@ifuchs @thanneman79 
I just ran this for the first time and was seeing the 100 event limit too. After looking closer at the documentation [here](https://python-ring-doorbell.readthedocs.io/index.html#ring_doorbell.stickup_cam.RingStickUpCam.history) there is an "older_than" parameter that you can pass to history that will get you the next set of data older than the event id specified. So, you call history the first time without specifying "older_than" which gives you an initial set. From there, continue calling history (with "older_than" specified now) until no further records are returned. Specify the id of the oldest (last) event in the current set when making subsequent calls to history.

**Comment by jr-ring** [comment]
I am the CTO @ Ring and we'd love to help you get this working to remove the unnecessary polling.  Please reach out to me at jr@ring.com

**Comment by 4Dolio** [comment]
I encountered this limit, but found there is also a $start-event (for past event count) call.  So I solved this be using the oldest known event I'd in order to build a local index of older events up to the 3month Ring storage limit... Hope that pseudo code helps.
