### ISSUE TITLE
Ring alerts API (active dings) is not device specific

### ISSUE THREAD

**Issue by ZachBenz** [tchellomello/python-ring-doorbell#170]
Currently, the alert/active dings API is used in a per-device check_alerts method.  An issue with this is that the Ring alerts API is not device specific - that is, when querying it, you get the most recent active alert across any device associated with the Ring account.  Thus, for example, when calling check_alerts on a doorbell, the alert you get back may in fact be for a completely different device.

I see at least two possible ways to address this:

1. Migrate check_alerts up from being a device specific call to being a global call
1. Keep check_alerts where it is, but filter out alerts if they aren't for the device being queried

**Comment by ZachBenz** [comment]
I'm going to take a crack at option 2 (keep check_alerts where it is for now, filter results) and see how that works out.

**Comment by nuketownhf** [comment]
This happens if you have multiple Ringdoorbells
The issue is located on  #138 
@tchellomello has to sort the IDs by order to have them fixed in position
