### ISSUE TITLE
Issues with token refresh requests

### ISSUE THREAD

**Issue by henriquechehad** [tchellomello/python-ring-doorbell#174]
Hello, 

It's sending refresh token requests for every API call. It should refresh the token only when the access token expires.

**Comment by steve-gombos** [comment]
I think this was resolved by #167 

Are you still seeing this after 0.2.9?

**Comment by henriquechehad** [comment]
Yes. It was sending new access token requests for every api call, after the changes it's sending refresh token request for every api call now.

**Comment by steve-gombos** [comment]
@henriquechehad I'll take a look later this evening.

**Comment by 4Dolio** [comment]
Could this be related to some access problems I am having?  About Dec 18th I began getting 503 errors, turns out I had changed my password, and also needed to update your library and then it worked again.  But now today at Jan 9 10:44:14 PST 2020 was the last time I could successfully connect, as of Jan 9 11:16:05 PST 2020 all attempts to connect now result with:

> File ".../lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in validate_token_parameters
> raise MissingTokenError(description="Missing access token parameter.")
> oauthlib.oauth2.rfc6749.errors.MissingTokenError:` (missing_token) Missing access token parameter.

I am wondering if Ring has changed their API? again?  I do not have 2FA enabled, yet, might that help? How does that work with your library?

**Comment by steve-gombos** [comment]
Looks like something is going on.  Seeing the same thing on my HA and just testing with the repo itself.  Debugging right now.

**Comment by SylvainGa** [comment]
Just want to add my voice to the group that are having issues.

**Comment by steve-gombos** [comment]
Looks like the Ring API is blocking the User-Agent again.  @balloob Would you know if they are blocking this lib again?

**Comment by steve-gombos** [comment]
https://github.com/home-assistant/home-assistant/issues/30626

**Comment by Kussie** [comment]
Can confirm the changes in the above PR (#176) solved the issue for me.

**Comment by andystewart999** [comment]
> Can confirm the changes in the above PR (#176) solved the issue for me.

Hey Kussie - I’m a bit of a noob with HA, how do I integrate this change before it’s baked in?

**Comment by tzbailey** [comment]
Is this something Ring does regularly in an attempt to stop projects like this?
Also, once the fix is committed, will it be available via pip for update?

**Comment by brama1966** [comment]
> > Can confirm the changes in the above PR (#176) solved the issue for me.
> 
> Hey Kussie - I’m a bit of a noob with HA, how do I integrate this change before it’s baked in?

You can wait till marcelo commits it or you would have to download it from Steve branch
Extract the ring_doorbell folder and copy that to you config folder.
docker into your homeassistant and copy it over to the existing ring-doorbell library folder.

**Comment by henriquechehad** [comment]
> Is this something Ring does regularly in an attempt to stop projects like this?

Ring is not attempting to stop this project. It just should fix the issue in the OAuth flow as described in the issue description above, so it would be OK.

**Comment by steve-gombos** [comment]
I think the main thing is that 0.2.9 hasn't been released in HA yet, I'm assuming that HA 0.104 should have this.  That fixes the repeated auth requests, which has gotten the oauthlib user agent blocked.

**Comment by SylvainGa** [comment]
> 
> 
> > > Can confirm the changes in the above PR (#176) solved the issue for me.
> > 
> > 
> > Hey Kussie - I’m a bit of a noob with HA, how do I integrate this change before it’s baked in?
> 
> You can wait till marcelo commits it or you would have to download it from Steve branch
> Extract the ring_doorbell folder and copy that to you config folder.
> docker into your homeassistant and copy it over to the existing ring-doorbell library folder.

Hi, I'm on hassio, is the process the same? I'm not seeing any ring files in my /config folder. Will the file deposited there override original file somewhere else?

I'm getting closer and closer to dropping this hassio annoyance and going to a manual instance since hassbian is no longer being supported...

**Comment by ZachBenz** [comment]
Just incorporated the 0.4.0 release into my Indigo Home Automation Server plugin, and so far, problems resolved.

**Comment by balloob** [comment]
For Home Assistant users: 0.104.0b3 will include a fix for Ring.
