### ISSUE TITLE
NameError: name 'token_updated' is not defined

### ISSUE THREAD

**Issue by ravishankarbs** [tchellomello/python-ring-doorbell#182]
Getting this error when trying to authenticate with my Ring device with credentials.

NameError: name 'token_updated' is not defined

Anyone else has this issue?

**Comment by dlemmink** [comment]
What was your resolution?  I had the same error with the new libraries.

**Comment by steve-gombos** [comment]
I assume you are working off of an example from test.py?  A token_updater method is passed into auth, which contains logic for saving your token for reuse.

**Comment by 4Dolio** [comment]
I am still having trouble, after switching from the main page example, and the older documentation example, and now looking at the test.py example.  When I use the test.py I get this error.

> Username: me@internet.net
> Traceback (most recent call last):
>   File "./ring.basic.py", line 147, in <module>
>     main()
>   File "./ring.basic.py", line 132, in main
>     username = input("Username: ")
>   File "<string>", line 1
>     me@internet.net
>        ^
> SyntaxError: invalid syntax

OR this:
> Username: asdf
> Traceback (most recent call last):
>   File "./ring.basic.py", line 147, in <module>
>     main()
>   File "./ring.basic.py", line 132, in main
>     username = input("Username: ")
>   File "<string>", line 1, in <module>
> NameError: name 'asdf' is not defined


Previously I had my own wrapper .py script that would just scrape(download) all my clips if I did not already have the file, for archival sake, nothing more.  That script takes my own set of arguments, including my username(email) and password, and I do not have 2fa enabled for my account, yet.  Commenting out those two input lines asking for username and password, that it seems I can not input, does not help, results in 
> Traceback (most recent call last):
>   File "./ring.basic.py", line 147, in <module>
>     main()
>   File "./ring.basic.py", line 136, in main
>     auth = Auth(None, token_updated)
>   File "/usr/local/lib/python2.7/dist-packages/ring_doorbell/auth.py", line 21, in __init__
>     client=LegacyApplicationClient(client_id=OAuth.CLIENT_ID), token=token
>   File "/home/foo/.local/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line > 79, in __init__
>     self.token = token or {}
>   File "/home/foo/.local/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line > 129, in token
>     self._client.populate_token_attributes(value)
>   File "/home/foo/.local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 492, in populate_token_attributes
>     if 'access_token' in response:
> TypeError: argument of type 'function' is not iterable

I also attempted to restore the past `.ring_doorbell-session.cache` file to see how that behaved and got this:
> Traceback (most recent call last):
>   File "./ring.basic.py", line 148, in <module>
>     main()
>   File "./ring.basic.py", line 129, in main
>     json.loads(cache_file.read_text()),
> AttributeError: 'PosixPath' object has no attribute 'read_text'
