### ISSUE TITLE
Feature request: Change Chime ring

### ISSUE THREAD

**Issue by syphernl** [tchellomello/python-ring-doorbell#19]
In the Ring app it is possible to change the sound the Chime should use. With this we can change the volume, but it would be nice if the sound could be changed as well.

**Comment by tchellomello** [comment]
Good idea @syphernl!

**Comment by tchellomello** [comment]
@syphernl could you test the PR https://github.com/tchellomello/python-ring-doorbell/pull/29  to see if works for you?

Thank you
