### ISSUE TITLE
TypeError: __init__() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by galadril** [tchellomello/python-ring-doorbell#190]
Im getting the next exception after updateing ring_doorbell to the latest version via pip (to 0.6.0).

### TypeError: __init__() takes 2 positional arguments but 3 were given

```
Traceback (most recent call last):
  File "RingCam.py", line 58, in <module>
    connectToRingAPI()
  File "RingCam.py", line 11, in connectToRingAPI
    myring = Ring('username', 'password')
```

Im using Python 3.6 at the moment..
Any ideas??

**Comment by d0ugal** [comment]
I believe you are hitting the breaking change described in the 0.4.0 release notes.

https://github.com/tchellomello/python-ring-doorbell/releases/tag/0.4.0

See the with work there

**Comment by steve-gombos** [comment]
Several breaking changes on 0.6.0 to fix oauth and data refactoring. Test.py and documentation should guide in the right direction.

**Comment by galadril** [comment]
Thanks, ive tried to test the test.py  but i get the next exception:
TypeError: argument of type 'function' is not iterable

```


Traceback (most recent call last):
  File "test.py", line 46, in <module>
    main()
  File "test.py", line 31, in main
    auth = Auth(None, token_updated)
  File "/usr/local/lib/python3.6/site-packages/ring_doorbell/auth.py", line 21, in __init__
    client=LegacyApplicationClient(client_id=OAuth.CLIENT_ID), token=token
  File "/usr/local/lib/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 79, in __init__
    self.token = token or {}
  File "/usr/local/lib/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 129, in token
    self._client.populate_token_attributes(value)
  File "/usr/local/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 492, in populate_token_attributes
    if 'access_token' in response:
TypeError: argument of type 'function' is not iterable

```

**Comment by steve-gombos** [comment]
Yeah #189 is the cause of this. The user agent is missing when creating the Auth object.

**Comment by galadril** [comment]
Thanks for the assistance.. i just passed the authorization.
But now i need to get my doorbells. The [readme ](https://github.com/tchellomello/python-ring-doorbell#showing-door-) states:

`doorbell = myring.doorbells[0]`


looking through the code, i think it should be something like:

 ```
   ring.update_data()
    ring.devices()    
    doorbell = ring.devices()["doorbells"][0]
```


But this gives a KeyError.

I think that i dont call the devices() method correctly.. can you please advise?

**Comment by galadril** [comment]
File "test.py", line 43
    {'doorbots': [<RingDoorBell: Front Door>]}
                  ^
SyntaxError: invalid syntax


How should i init that devices() method??

**Comment by galadril** [comment]
Got it working, thanks!
```

    ring = Ring(auth)
    ring.update_data()
    data = ring.devices()
    doorbell = data["doorbots"][0]
```

**Comment by itadministrator-bhab** [comment]
Hi Galadril, where do you enter this code?
I just tried the following code and I got the same error message. (    if 'access_token' in response:
TypeError: argument of type 'function' is not iterable)
Thanks

import json
from pathlib import Path

from ring_doorbell import Ring, Auth


cache_file = Path('test_token.cache')


def token_updated(token):
    cache_file.write_text(json.dumps(token))


def otp_callback():
    auth_code = input("2FA code: ")
    return auth_code


def main():
    if cache_file.is_file():
        auth = Auth(json.loads(cache_file.read_text()), token_updated)
    else:
        username = input("Username: ")
        password = input("Password: ")
        auth = Auth(None, token_updated)
        auth.fetch_token(username, password, otp_callback)

    ring = Ring(auth)
    print(ring.devices)


if __name__ == '__main__':
    main()
> Got it working, thanks!
> 
> ```
> 
>     ring = Ring(auth)
>     ring.update_data()
>     data = ring.devices()
>     doorbell = data["doorbots"][0]
> ```

**Comment by itadministrator-bhab** [comment]
This code worked for me: 
import json
import getpass
from pathlib import Path

from ring_doorbell import Ring, Auth
from oauthlib.oauth2 import MissingTokenError


cache_file = Path("test_token.cache")


def token_updated(token):
    cache_file.write_text(json.dumps(token))


def otp_callback():
    auth_code = input("2FA code: ")
    return auth_code


def main():
    if cache_file.is_file():
        auth = Auth("MyProject/1.0", json.loads(cache_file.read_text()), token_updated)
    else:
        username = input("Username: ")
        password = getpass.getpass("Password: ")
        auth = Auth("MyProject/1.0", None, token_updated)
        try:
            auth.fetch_token(username, password)
        except MissingTokenError:
            auth.fetch_token(username, password, otp_callback())

    ring = Ring(auth)
    ring.update_data()

    devices = ring.devices()
    print(devices)

    doorbells = devices["doorbots"]
    chimes = devices["chimes"]
    stickup_cams = devices["stickup_cams"]

    print(doorbells)
    print(chimes)
    print(stickup_cams)

    devices = ring.devices()
    doorbell = devices['doorbots'][0]
    doorbell.recording_download(
    doorbell.history(limit=100, kind='ding')[0]['id'],
                     filename='last_ding.mp4',
                     override=True)


if __name__ == "__main__":
    main()

**Comment by itadministrator-bhab** [comment]
I was able to run it for more videos with this code:
import json
import getpass
from pathlib import Path

from ring_doorbell import Ring, Auth
from oauthlib.oauth2 import MissingTokenError


cache_file = Path("test_token.cache")


def token_updated(token):
    cache_file.write_text(json.dumps(token))


def otp_callback():
    auth_code = input("2FA code: ")
    return auth_code


def main():
    if cache_file.is_file():
        auth = Auth("MyProject/1.0", json.loads(cache_file.read_text()), token_updated)
    else:
        username = input("Username: ")
        password = getpass.getpass("Password: ")
        auth = Auth("MyProject/1.0", None, token_updated)
        try:
            auth.fetch_token(username, password)
        except MissingTokenError:
            auth.fetch_token(username, password, otp_callback())

    ring = Ring(auth)
    ring.update_data()

    devices = ring.devices()
    # print(devices)

    # doorbells = devices["doorbots"]
    # chimes = devices["chimes"]
    stickup_cams = devices["stickup_cams"]

    # print(doorbells)
    # print(chimes)
    print(stickup_cams)

    devices = ring.devices()
    doorbell = devices['stickup_cams'][0]
    doorbell.recording_download(
    doorbell.history(limit=100, kind='motion')[0]['id'],
                     filename='last_ding00.mp4',
                     override=True)
    doorbell.recording_download(
    doorbell.history(limit=100, kind='motion')[4]['id'],
                     filename='last_ding01.mp4',
                     override=True)

    doorbell = devices['stickup_cams'][1]
    doorbell.recording_download(
    doorbell.history(limit=100, kind='motion')[0]['id'],
                     filename='last_ding10.mp4',
                     override=True)
    doorbell.recording_download(
    doorbell.history(limit=100, kind='motion')[4]['id'],
                     filename='last_ding11.mp4',
                     override=True)         

    doorbell = devices['stickup_cams'][2]
    doorbell.recording_download(
    doorbell.history(limit=100, kind='motion')[0]['id'],
                     filename='last_ding20.mp4',
                     override=True)
    doorbell.recording_download(
    doorbell.history(limit=100, kind='motion')[4]['id'],
                     filename='last_ding21.mp4',
                     override=True)  
    
    doorbell = devices['stickup_cams'][3]
    doorbell.recording_download(
    doorbell.history(limit=100, kind='motion')[0]['id'],
                     filename='last_ding30.mp4',
                     override=True)
    doorbell.recording_download(
    doorbell.history(limit=100, kind='motion')[4]['id'],
                     filename='last_ding31.mp4',
                     override=True)

    doorbell = devices['stickup_cams'][4]
    doorbell.recording_download(
    doorbell.history(limit=100, kind='motion')[0]['id'],
                     filename='last_ding40.mp4',
                     override=True)
    doorbell.recording_download(
    doorbell.history(limit=100, kind='motion')[4]['id'],
                     filename='last_ding41.mp4',
                     override=True)

    doorbell = devices['stickup_cams'][5]
    for n in range(100):
        doorbell.recording_download(
        doorbell.history(limit=100, kind='motion')[n]['id'],
                     filename='last_ding5'+n+'.mp4',
                     override=True)
   




if __name__ == "__main__":
    main()
