### ISSUE TITLE
Ring Account verification

### ISSUE THREAD

**Issue by knlklabacka** [tchellomello/python-ring-doorbell#197]
I did look through the old issues and searched for this issue.  I have 2FA turned off on my ring account.  Every time I run my script I get auth error.  I also get an email from ring to verify my account.

`
Traceback (most recent call last):
  File "/home/mdk177/Documents/Python/ring_download.py", line 81, in <module>
    main()
  File "/home/mdk177/Documents/Python/ring_download.py", line 26, in main
    auth.fetch_token(data['ring'][0]['username'], s.string_decrypt(data['ring'][0]['password']))
  File "/usr/local/lib/python3.7/dist-packages/ring_doorbell/auth.py", line 40, in fetch_token
    headers=headers,
  File "/usr/local/lib/python3.7/dist-packages/requests_oauthlib/oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.7/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.7/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.7/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.
`

Can anyone help me out please??

**Comment by steve-gombos** [comment]
I'm pretty sure ring has made 2FA enabled for everyone within the last day or so.

**Comment by jr-ring** [comment]
Do you have a path to resolve this and/or do you need to coordinate with us at Ring?  If so, please send me an email to jr@ring.com and we are happy to discuss solutions to you supporting 2FA properly.  Thanks.

**Comment by steve-gombos** [comment]
@jr-ring 2FA was added at the end of Dec/Jan.  This lib should be good for phone codes (tested with my account), but I haven't verified with an email code.   I assume email should work just fine.   

@knlklabacka I recommend you verify your script against the docs.  You will need to implement 2FA into the script you are executing.  Something along the lines of test.py.  oauthlib returns a MissingTokenError that we catch and prompt for 2FA, I am assuming this isn't the case with your script.

**Comment by knlklabacka** [comment]
@steve-gombos my script was to once a day download doorbell motions.  I would like this to happen without user input.  Any suggestions??

**Comment by steve-gombos** [comment]
You will need to manually auth at least once to get an access token since 2FA is required now.  Then the script will need to implement the token updater to save the access token into a cache file. After that you should be able to just run as usual and the refresh token will be used to generate a new access token. The test.py file and docs are a good place to see this.

**Comment by knlklabacka** [comment]
Thank you for the help.  I have this working!!
