### ISSUE TITLE
[Help wanted] Having trouble with authentication 

### ISSUE THREAD

**Issue by carlwain74** [tchellomello/python-ring-doorbell#198]
Hi there,

I’m not an expert python developer so excuse myself.

Could someone share with me the best way to authenticate with 2fa enabled?

I had basic authentication working for a while and then Ring started sending me email codes and my script broke.

I saw news about ring security so decided to enable 2fa in my account. However, after reading the docs I’m clueless about what to do.
I tried to integrate a callback function, but I don’t get a code delivered after callback is invoked. Without the callback the SMS is sent, but I have no means to enter it in.

My script is designed to report on battery status for my outdoor stickup cams so I know when to start swapping them out.

Any help would be appreciated.
Cheers
Carl

**Comment by steve-gombos** [comment]
Test.py shows how you would auth.

https://github.com/tchellomello/python-ring-doorbell/blob/master/test.py

You first need to call the fetch token method on auth with your credentials. This will throw a MissingTokenError you need to catch. In the catch you call fetch token again but use the callback to receive input of the 2FA code. Also important to save the access code to refresh tokens after expiration.

**Comment by carlwain74** [comment]
I totally missed that example. I’ll check that out and see how I get on.

**Comment by carlwain74** [comment]
Awesome, now it works.
