### ISSUE TITLE
Changing the history from 100 to a greater number

### ISSUE THREAD

**Issue by itadministrator-bhab** [tchellomello/python-ring-doorbell#200]
Hi, thank you so much for sharing this amazing tool, do you have a way to change the code to a greater number to get more videos please? 
This only returns 100 max. 
Thank you!

import json
import getpass
from pathlib import Path

from ring_doorbell import Ring, Auth
from oauthlib.oauth2 import MissingTokenError

cache_file = Path("test_token.cache")

def token_updated(token):
    cache_file.write_text(json.dumps(token))

def otp_callback():
    auth_code = input("2FA code: ")
    return auth_code

def main():
    if cache_file.is_file():
        auth = Auth("MyProject/1.0", json.loads(cache_file.read_text()), token_updated)
    else:
        username = input("Username: ")
        password = getpass.getpass("Password: ")
        auth = Auth("MyProject/1.0", None, token_updated)
        try:
            auth.fetch_token(username, password)
        except MissingTokenError:
            auth.fetch_token(username, password, otp_callback())

    ring = Ring(auth)
    ring.update_data()

    devices = ring.devices()
    # print(devices)

    # doorbells = devices["doorbots"]
    # chimes = devices["chimes"]
    stickup_cams = devices["stickup_cams"]

    # print(doorbells)
    # print(chimes)
    print(stickup_cams)

    devices = ring.devices()
    doorbell = devices['stickup_cams'][0]
    doorbell.recording_download(
    doorbell.history(limit=100, kind='motion')[99]['id'],
                     filename='last_ding00.mp4',
                     override=True)

if __name__ == "__main__":
    main()

**Comment by steve-gombos** [comment]
I can't tell if you are trolling or not.  You have opened two issues that aren't really issues from what I can tell, and #199 has been edited about 10 times,  I'm going to be closing both.  If you have an actual issue to report please open another issue with relevant errors, stack trace, etc...

To add additional information, ring only stores video for the last 60 days, so you can set the limit as high as you want, but it will only return 60 days worth of events.

https://shop.ring.com/pages/faq

**Comment by itadministrator-bhab** [comment]
Hi Steve, thanks for the link and sorry for the numerous edits. It was because I was figuring out how to solve the issue and was updating the code. 
The challenge is to get more than the count of 100. It seems that the current code only returns 100 items not 100 days (even given the limit of 60 days). 
If the limit is changed to 1000 for example, no matter what the videos won't be returned.
doorbell.history(limit=1000, kind='motion')[105]['id'],
                 filename='last_ding00.mp4',
                 override=True) 
How do I return the videos past the limit of 100?
Thanks


Code used that goes to the last item retrievable:
---------

import json
import getpass
from pathlib import Path

from ring_doorbell import Ring, Auth
from oauthlib.oauth2 import MissingTokenError

cache_file = Path("test_token.cache")

def token_updated(token):
cache_file.write_text(json.dumps(token))

def otp_callback():
auth_code = input("2FA code: ")
return auth_code

def main():
if cache_file.is_file():
auth = Auth("MyProject/1.0", json.loads(cache_file.read_text()), token_updated)
else:
username = input("Username: ")
password = getpass.getpass("Password: ")
auth = Auth("MyProject/1.0", None, token_updated)
try:
auth.fetch_token(username, password)
except MissingTokenError:
auth.fetch_token(username, password, otp_callback())

ring = Ring(auth)
ring.update_data()

devices = ring.devices()
# print(devices)

# doorbells = devices["doorbots"]
# chimes = devices["chimes"]
stickup_cams = devices["stickup_cams"]

# print(doorbells)
# print(chimes)
print(stickup_cams)

devices = ring.devices()
doorbell = devices['stickup_cams'][0]
doorbell.recording_download(
doorbell.history(limit=100, kind='motion')[99]['id'],
                 filename='last_ding00.mp4',
                 override=True)
if name == "main":
main()

**Comment by steve-gombos** [comment]
See #63.  Ring limits the API call to 100 regardless of what is passed.  You must use the older_than param set to the last history event ID in the array.

**Comment by itadministrator-bhab** [comment]
Thanks Steve, I tried using #63 but I get the following error message: No name 'URL_DOORBELL_HISTORY' in module 'ring_doorbell' when following the example from #63 
history=doorbell._ring.query(API_URI + URL_DOORBELL_HISTORY.format(doorbell.account_id), extra_params={'older_than':history[-1]['id']})
How do you pass the parameter in the following case 
for n in range(99,15000):
        doorbell.recording_download(
        doorbell.history(limit=15000, kind='motion')[n]['id'],
                     filename='last_ding001'+str(n)+'.mp4',
                     override=True) ? 
Thank you

**Comment by steve-gombos** [comment]
Best I can give you is this:

```
history = doorbells[0].history(limit=50)
print(len(history))
newHistory = doorbells[0].history(limit=100, older_than=history[49]['id'])
print(len(newHistory))
```

**Comment by itadministrator-bhab** [comment]
Thanks. Just tried this : 
`
  devices = ring.devices()
    doorbell = devices['stickup_cams'][0]
    history = devices['stickup_cams'][0].history(limit=100)
    print(len(history))
    doorbell.recording_download(
    doorbell.history(limit=1000, kind='motion', older_than=history[49]['id'])[101]['id'],
                     filename='last_ding00.mp4',
                     override=True
                               )`

I get the following error message: "doorbell.history(limit=1000, kind='motion', older_than=history[49]['id'])[101]['id'],
IndexError: list index out of range"

My goal is to download all the videos.

**Comment by steve-gombos** [comment]
I'd assume to do what you want, you will have to get history up to the limit, at the last index of the array, you will save that history event id, then you will call doorbell.history setting the older_than query string param equal to the history event id, then you will loop over that set of history events, and you will basically do that until your done.

**Comment by itadministrator-bhab** [comment]
Thanks. So I tried the following and I am able to go past 100 videos but the connection to Ring resets at random times for some reason and then I have to start the download all over. How does one start the  download not from the present time but from a a week ago for example?
Thank you
`    while len(history) > 0:
            print(
                "\tProcessing and downloading the next videos"
            )

            counter = 0
            for event in history:
                counter += 1
                filename='last_ding001'+str(counter)+ str(doorbell.last_recording_id) +'.mp4'
                print("Downloading "+ str(counter))

                doorbell.recording_download(
                    event["id"], filename=filename, override=False
                )

            history = doorbell.history(limit=100, older_than=history[-1]["id"])
if __name__ == "__main__":
    main()
`

**Comment by steve-gombos** [comment]
Sounds like you need to write a smarter script. You probably need to accomplish what you are trying in multiple parts. One is extracting all of the events to storage. Second is to then worry about downloading, and as you download you can update the storage with those that you have downloaded as you go. That way you can check if you have downloaded them previously and just skip. This to me isn't an issue with the library, so can't really help much more.

**Comment by itadministrator-bhab** [comment]
I agree. In words it seems very easy to do... I think a smarter script would also be to capture the last failed one and start from there instead of going through the entire sequence of downloads. 
I tried the following but it still downloaded from the most recent event. 

` while len(history) > 0:
            print(
                "\tProcessing and downloading the next videos"
            )

            counter = 0
            for event in history:
                counter += 1
                filename='Video001'+str(counter)+ str(randint(1,10))+ str(event["id"]) +'.mp4'
                print("Downloading "+ str(counter))
                print(event["id"])

                doorbell.recording_download(
                    event["id"], filename=filename, override=False
                )

            history = doorbell.history(limit=100, older_than=history[6799740619029108920]["id"])`

**Comment by 4Dolio** [comment]
I will try to post my script.  But the gist of it is I save my videos as DevName_Date_EventID.mp4, this way O can ask my script to download any date for which I already have a download, which you slowly get as you download them all backwards in time...  To get days I missed, I give it an array of dates, going backwards, by 1hour intervals, starting at the oldest clip I already have.  I won't be able to get to my code for a few days though, perhaps my pseudo procedure will help?

**Comment by itadministrator-bhab** [comment]
Thank you very much for your offer to help. I can wait a few days for a working code. 
I tried a similar approach (tracking the last id) but the code to request videos older than the last id that worked still starts with the download of the most recent video instead of getting the videos older than that video. 
` while len(history) > 0:
print(
"\tProcessing and downloading the next videos"
)

        counter = 0
        for event in history:
            counter += 1
            filename='Video001'+str(counter)+ str(randint(1,10))+ str(event["id"]) +'.mp4'
            print("Downloading "+ str(counter))
            print(event["id"])

            doorbell.recording_download(
                event["id"], filename=filename, override=False
            )

        history = doorbell.history(limit=100, older_than=history[6799740619029108920]["id"])`

**Comment by 4Dolio** [comment]
Shrugs... Yes, it might also always download the newest clips, I'm not sure, but you want those also anyway?

**Comment by itadministrator-bhab** [comment]
I'm ok with getting the most recent ones as long as I am able to get all the videos. The problem is that the code crashes for some reason and then I have to restart the download and hope it doesn't crash.

**Comment by itadministrator-bhab** [comment]
FYI. In my attempt to start the download from a previous day instead of the most current, I used the following code but I get the following error message: "history = doorbell.history(limit=100, older_than=history[6799740619029108920]["id"])
IndexError: list index out of range"

`    devices = ring.devices()
    doorbell = devices['stickup_cams'][0]
    history = devices['stickup_cams'][0].history(limit=100)
    history = doorbell.history(limit=100, older_than=history[6799740619029108920]["id"])
    print(len(history))

    print(doorbell.recording_url(doorbell.last_recording_id))

   

    while len(history) > 0:
            print(
                "\tProcessing and downloading the next videos"
            )

            counter = 0
            for event in history:
                counter += 1
                filename='Video001'+str(counter)+ str(randint(1,10))+ str(event["id"]) +'.mp4'
                print("Downloading "+ str(counter))
                print(event["id"])

                doorbell.recording_download(
                    event["id"], filename=filename, override=False
                )`

**Comment by itadministrator-bhab** [comment]
Also, does anyone know if there's a way to specify a specific camera by its name? It seems that the index for the camera changes as new events occur. For example doorbell = devices['stickup_cams'][0] refers to camera A currently but will refer to camera B at a later time. I am looking for something like doorbell = devices['stickup_cams'][A] but this won't work as it's for an index. 
Thanks

**Comment by 4Dolio** [comment]
The older_than index must be valid for one of your clips.  I attempted an arbitrary value and that does not work, returns the error you got.  Also, my script also crashes periodically.  Sometime it does not get any good data, sometime is gets some clips and then crashes, most of the time it works fine.  So you will need to handle that, I do so by calling my .py scrips from a shell loop with appropriate sleep delays.

**Comment by itadministrator-bhab** [comment]
Thank you so much for looking into this and sharing your experience. So here's the proper call for the index: 
history = doorbell.history(limit=100, older_than='6799740619029108920') 
I was using : history = doorbell.history(limit=100, older_than=history[6799740619029108920]["id"])
Both had the valid event id. The proper way to call it is:
history = doorbell.history(limit=100, older_than='6799740619029108920') 
Thanks again for your help. I am now at least getting older videos instead of starting from today every time. I'll just keep track of the last video that the scrip was able to obtain. Thanks!

**Comment by itadministrator-bhab** [comment]
At this point the one thing that would be helpful would be able to specify which camera. It seems that the index for the camera changes as new events occur. For example
doorbell = devices['stickup_cams'][0] refers to camera A currently but will refer to camera B at a later time. I am looking for something like doorbell = devices['stickup_cams'][A] but this won't work as it's for an index.
Thanks

**Comment by 4Dolio** [comment]
Ok, here is my script.  I am a sysadmin, so this is rather Bash centric, a lot of the safeties are due to running it from a shell with timeouts and loops and sleeps, YMMV. 

https://github.com/4Dolio/python-ring-doorbell/blob/master/RingFetchPub.py
