### ISSUE TITLE
404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by thanneman79** [tchellomello/python-ring-doorbell#205]
I'm in the process of revamping my Ring Video archiver script to use the new 2FA. I believe I've got that part down, however I get the following error randomly.

ring_doorbell.doorbot - ERROR - 404 Client Error: Not Found for url: https://api.ring.com/clients_api/dings/[RING EVENT REDACTED]/recording?api_version=9
Traceback (most recent call last):

**Comment by thanneman79** [comment]
The download function also seems slower now.

**Comment by knlklabacka** [comment]
I'm having the same issue.

**Comment by knlklabacka** [comment]
Was there a fix for this?  Or was this issue resolved?  I'm having the same error as of today.

**Comment by thanneman79** [comment]
I still get it randomly to this day. Been awhile since I implemented a work around on my side. If I recall it'll happen over and over on the same event. My code will move on to the next event.

**Comment by knlklabacka** [comment]
I'm wondering if anyone has figured this issue out?

**Comment by minhio** [comment]
same here, intermittently getting `requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.ring.com/clients_api/dings/<redacted>/recording?api_version=9`

**Comment by likan999** [comment]
Seeing the same here. If I stop my program of downloading videos and try again a little later, then it works for the few videos and then 404 again. I guess Ring has some throttle on their side. Is it something the library can handle transparently, or caller has to handle it manually?

**Comment by nhet** [comment]
Same here. Tested with 0.6.2 and 0.7.0 of this lib

**Comment by nhet** [comment]
I can't belive that Ring has some throttle on their side. When I use the official Ring app the videos are after a few seconds available. I thing they have changed the api.

**Comment by thanneman79** [comment]
As far as I have been able to tell its not throttling. And only seems to occur on certain videoes.

**Comment by nhet** [comment]
It's interesting and strange at the same time. The downloads often work after exactly 30 minutes.

**Comment by thanneman79** [comment]
So I'm looking at this one again because I've noticed this is happening in my logs far more often now that I've added additional cameras to my account. If I rerun the the code it will successfully download that file. My best guess now it some kind of throttling on the server side. Looking at throttling downloads to improve reliability.

**Comment by krishxmatta** [comment]
Has anyone found a solution?

**Comment by abatada** [comment]
Does anyone have experience with this?

**Bulk Download Ring Camera Videos and Store in AWS S3**
https://medium.com/@embracethesuck/bulk-download-ring-camera-videos-and-store-in-aws-s3-2060e5838426

**Comment by likan999** [comment]
> Does anyone have experience with this?
> 
> **Bulk Download Ring Camera Videos and Store in AWS S3** https://medium.com/@embracethesuck/bulk-download-ring-camera-videos-and-store-in-aws-s3-2060e5838426

Yeah I wrote some program to download my videos and then I was hit by this error and seems like Ring has placed throttling on it.
