### ISSUE TITLE
Question usage

### ISSUE THREAD

**Issue by rolands123** [tchellomello/python-ring-doorbell#212]
Hello, 

I did try this library, and it is working great! Thanks for that. However i have some questions:

1. Is it possible to only download the video with "doorbell.recording_download" when the last download is older than the available one or somehow validate since the last motion.
2. In the example for "doorbell.recording_download" there is a limit=100 displayed, however, as I understand, it is always downloading the last event based on the "kind" filter, why is this limit included? 
3. I cannot get the "get_napshot" working, is there some example code available, e.g. like for the "doorbell.recording_download"?

Best regards,
Roland

**Comment by 4Dolio** [comment]
I do this test client side.  Save all clips in a known format and just test that it exists before calling the download.
