### ISSUE TITLE
live_streaming_json returns "None"

### ISSUE THREAD

**Issue by clinkadink** [tchellomello/python-ring-doorbell#219]
I couldn't work out why `live_streaming_json` was returning "None" all the time. On further investigation, it seems as if the endpoint has changed. Instead of ending in `/vod` it now ends in `/live_view`

In const.py, I have changed:
From this: `LIVE_STREAMING_ENDPOINT = DOORBELLS_ENDPOINT + "/vod"`
To this: `LIVE_STREAMING_ENDPOINT = DOORBELLS_ENDPOINT + "/live_view"`

I thought that was the only issue, but for some reason, it still returned "None". The existing function checks for status code of 204 returned by the query. I am not getting this, so once I removed that part of the if statement, it correctly returned the live streaming json.

I changed this:
```
def live_streaming_json(self):
        """Return JSON for live streaming."""
        url = LIVE_STREAMING_ENDPOINT.format(self.id)
        req = self._ring.query(url, method="POST")
        if req and req.status_code == 204:         <----- this line was preventing a correct JSON response
            url = DINGS_ENDPOINT
            try:
                return self._ring.query(url).json()[0]
            except (IndexError, TypeError):
                pass
        return None

```
To this:
```
def live_streaming_json(self):
        """Return JSON for live streaming."""
        url = LIVE_STREAMING_ENDPOINT.format(self.id)
        req = self._ring.query(url, method="POST")
        if req:                                   <------- status code check removed = works fine
            url = DINGS_ENDPOINT
            try:
                return self._ring.query(url).json()
            except (IndexError, TypeError):
                pass
        return None
```

With these 2 changed, it now works (for me).

**Comment by kethan1** [comment]
Thank you very much, I forked this project and did the changes and it works :)

**Comment by kethan1** [comment]
I did have an issue with the URL, it did not work :(

**Comment by kethan1** [comment]
I just realized that this a SIP url, SIP is pretty much used for making calls and Ring uses this for two way audio and video.
