### ISSUE TITLE
Fails to connect to Ring

### ISSUE THREAD

**Issue by torbjorn-stabo** [tchellomello/python-ring-doorbell#221]
I'm getting
`WARNING (MainThread) [homeassistant.components.ring] Error fetching Ring device data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`
in home-assistant.log. Related to #177 ?

**Comment by clintonruairi** [comment]
Having the same issue. Clearing the cache of your browser appears to work temporarily. No perma-fix though.

**Comment by 1800Zeta** [comment]
Just popped on to say I am also having this issue, looks like someone has found a problem with the expiry of tokens?

https://github.com/home-assistant/core/issues/38025

**Comment by dwarf-rbi** [comment]
Having same issue
