### ISSUE TITLE
Requirement is pinned for ring-doorbell 0.6.0: requests==2.22.0

### ISSUE THREAD

**Issue by MartinHjelmare** [tchellomello/python-ring-doorbell#222]
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

**Comment by balloob** [comment]
Fixes in 59ae9b186df5b6b2ad2b87d92374738cb6b84b33

**Comment by MartinHjelmare** [comment]
`setup.py` still has pinned requirements:
https://github.com/tchellomello/python-ring-doorbell/blob/d20243aa19eb115ea2c7562ccb0b2bab864ebb3f/setup.py#L25-L28

When a new release is made it would be good to also bump in home assistant.

**Comment by balloob** [comment]
Fixed in 0.6.2
