### ISSUE TITLE
Active alerts not working?

### ISSUE THREAD

**Issue by soeters** [tchellomello/python-ring-doorbell#223]
Hi all,

In an infinite loop i'm checking for alerts each 2 seconds with:
```
myring.update_dings()
if myring.active_alerts() != []:
...
```
But when I press the ring, no alert is coming through (it does on the official app).
Am I missing something?  What is the definition of an active alert?

**Comment by riptidewave93** [comment]
I have found if you are hitting the endpoint too often it will fail to grab active alerts. Personally adding a 5 second sleep seems to work best in my testing, but results may vary.
