### ISSUE TITLE
Licence issue

### ISSUE THREAD

**Issue by graham33** [tchellomello/python-ring-doorbell#241]
Hi there,

I'm working on packaging this project in Nixpkgs (https://github.com/NixOS/nixpkgs/pull/114181) and we noticed that the [LICENSE](https://github.com/tchellomello/python-ring-doorbell/blob/master/LICENSE) file seems to be LGPL 2, but [setup.py](https://github.com/tchellomello/python-ring-doorbell/blob/master/setup.py#L23) indicates LGPL 3+.  We were wondering which licence we should indicate, and whether one or both of these should be updated?  Thanks!

**Comment by tchellomello** [comment]
Thanks for the heads up. It's consistent now

**Comment by graham33** [comment]
Great, thanks!
