### ISSUE TITLE
2FA code

### ISSUE THREAD

**Issue by krushil1** [tchellomello/python-ring-doorbell#265]
Not getting the 2FA code sent to me while running the setup

**Comment by martin-g-it** [comment]
Same here. I am able to retrieve this via: 
npx -i ring-client-api ring-auth-cli

**Comment by krushil1** [comment]
So, if you do it through **npx -i ring-client-api ring-auth-cli**, then do you get your 2FA code?

**Comment by martin-g-it** [comment]
Jup, used this for a different API

**Comment by krushil1** [comment]
Sweet! I will into it! Thx for sharing!

**Comment by martin-g-it** [comment]
So to get this library to work again, use the abo mentioned command to get the 2FA code.
Important: do NOT enter the code in the CLI, but put the code (received by text/email) in the script like https://github.com/tchellomello/python-ring-doorbell#initializing-your-ring-object .
Then run the scrpt and it will create the token.cache file with the token.

**Comment by krushil1** [comment]
Got it! Thank you :)
