### ISSUE TITLE
Your Ring account does not have an active subscription.

### ISSUE THREAD

**Issue by soygabrielme2** [tchellomello/python-ring-doorbell#266]
I was able to access the information on my Ring camera. However, when I tried to download or display one of the videos it says 'Your Ring account does not have an active subscription'.

any ideas?
![Capture](https://user-images.githubusercontent.com/98435457/161172813-df2f9c77-0360-4b15-b71c-9a196cd23864.JPG)

**Comment by soygabrielme2** [comment]
wrong syntax. Never mind

**Comment by eddyizm** [comment]
So is this supposed to work, eg without a subscription? I am assuming yes. Once i get a better understanding of the repo and functionality, I will attempt to contribute and address some bugs.
