### ISSUE TITLE
Browser version

### ISSUE THREAD

**Issue by ndg63276** [tchellomello/python-ring-doorbell#271]
I used this code to make a crude version that runs in a browser, see https://github.com/ndg63276/ring - any dev help welcome.

A working version is online at https://smartathome.co.uk/ring if anyone wants to try it out.

**Comment by jcsacto** [comment]
I tried it out...very cool tangible interpretation of the code! Can I assume that all of the 'toggles' you had available in there are all that is available in this API?  I'm looking to try and automate the Motion Warning toggle for one of my devices is why I ask.  Well done though, helps a non-coder like me see what's under the hood a little easier!
