### ISSUE TITLE
Function get_snapshot() in doorbot needs attention

### ISSUE THREAD

**Issue by mskoster** [tchellomello/python-ring-doorbell#272]
Line 441: if response["timestamps"][0]["timestamp"] / 1000 > request_time:
here the division by 1000 seems to be incorrect. I guess Ring changed the response format. Propose to change to
if response["timestamps"][0]["timestamp"] > request_time:

Line 443: SNAPSHOT_ENDPOINT.format(self._attrs.get("id")), raw=True
here the raw parameter is invalid in the call to self._ring.query().
Propose to change to
SNAPSHOT_ENDPOINT.format(self._attrs.get("id"))

Kind Regards,
Martin

**Comment by budachst** [comment]
Good catch! Thanks for sharing.

**Comment by ericm301** [comment]
I have made the above changes and still can't get any snapshots.

**Comment by nathankrueger** [comment]
The fix works for me!
