### ISSUE TITLE
2FA -  Not working

### ISSUE THREAD

**Issue by kooscode** [tchellomello/python-ring-doorbell#278]
When running the sample code the callback is invoked via `auth.fetch_token(username, password, otp_callback())` but i never receive any 2FA codes on my phone..

When I login manually on Ring website, it works fine and I can get 2FA codes.

**Comment by tispokes** [comment]
Same here

**Comment by tispokes** [comment]
@kooscode solved it. When you use the test script in the readme, you just have to change the Application name from "MyProject" into something different. Its refered on 2 places, just change it and it works fine

**Comment by kooscode** [comment]
YES - that worked!!  Thanks so much!
