### ISSUE TITLE
Tokens Seem To Expire After About An Hour

### ISSUE THREAD

**Issue by simmonyau** [tchellomello/python-ring-doorbell#283]
It seems like tokens are now expiring after about an hour even with calls to Auth.refresh_tokens.

**Comment by EnGamma** [comment]
@simmonyau Resolution?

**Comment by kooscode** [comment]
> Found workaround using pyotp

@simmonyau - can you perhaps share your workaround?  i have a service thats running in background that always needs the latest active token to automate lights.
