### ISSUE TITLE
Motion-detection command not present in 0.7.4

### ISSUE THREAD

**Issue by rcanetta** [tchellomello/python-ring-doorbell#294]
Hi
I have installed 0.7.4 but the motion-detection command is not recognised...

```
root@erd:/usr/local/lib/python3.9/site-packages# ring-doorbell --version
ring-doorbell, version 0.7.4
root@erd:/usr/local/lib/python3.9/site-packages# ring-doorbell motion-detection --device-name "LatoEst" --off
Usage: ring-doorbell [OPTIONS] COMMAND [ARGS]...
Try 'ring-doorbell --help' for help.

Error: No such command 'motion-detection'.
root@erd:/usr/local/lib/python3.9/site-packages# ring-doorbell --help
Usage: ring-doorbell [OPTIONS] COMMAND [ARGS]...

Command line function.

Options:
--username TEXT Username for Ring account.
--password TEXT Password for Ring account
--version Show the version and exit.
--help Show this message and exit.

Commands:
show Display ring devices.
videos Intercat with ring videos.
root@erd:/usr/local/lib/python3.9/site-packages#
```

Any idea what am I missing?

Thanks a lot,
Riccardo

**Comment by XlabNO** [comment]
That command was added two weeks ago, but the latest release is three weeks old. 

Install from repo instead and it will work :)

# Installing latest development
$ pip install \
    git+https://github.com/tchellomello/python-ring-doorbell@master

**Comment by rcanetta** [comment]
Hi @XlabNO  thanks a lot - I had actually tried that but without first uninstalling the release version... so all I had to do was uninstall and then install the repo version and it works!! Fantastic!!

Thanks a lot
Riccardo

**Comment by sdb9696** [comment]
Glad this is all working for you now
