### ISSUE TITLE
Doesn't work with shared doorbells/Chimes

### ISSUE THREAD

**Issue by GreenTurtwig** [tchellomello/python-ring-doorbell#31]
My Ring account has a doorbell that has been shared with me so I can get notifications, check the status through the app, e.t.c.
The problem lies when I ran `myring.devices` I expected one doorbell and a Chime to appear, unfortunately neither show up. I assume this has to do with the account having shared devices.  
Just wondering if this can be addressed as an issue.
Thanks :cat2:

**Comment by tchellomello** [comment]
Thanks for reporting this issue @GreenTurtwig.

I'll share my own account with a 2nd email address to see I can reproduce the issue. 

Let's see if we can get this fixed.

**Comment by GreenTurtwig** [comment]
Great, this is definitely a rare occurrence since people are more likely to own the device itself. I doubt all the features of the API are there, but at least there's still quite a bit of info. :cat2:

**Comment by tchellomello** [comment]
@GreenTurtwig  do you have those options on your Ring app on your phone?

**Comment by GreenTurtwig** [comment]
I can take a few screenshots for you.

**Comment by GreenTurtwig** [comment]
![screenshot_20170318-110120](https://cloud.githubusercontent.com/assets/15905797/24071483/e98f2020-0bca-11e7-9712-c8de1c931903.png)
![screenshot_20170318-110207_01](https://cloud.githubusercontent.com/assets/15905797/24071480/e98d8350-0bca-11e7-996a-4b9ead1e6bdc.png)
![screenshot_20170318-110155](https://cloud.githubusercontent.com/assets/15905797/24071482/e98e7efe-0bca-11e7-9c67-1e7c95dce8d7.png)
![screenshot_20170318-110216](https://cloud.githubusercontent.com/assets/15905797/24071481/e98df3b2-0bca-11e7-8d97-762279f2559c.png)
Yeah... They're pretty big...

**Comment by tchellomello** [comment]
I've shared my account with a second email and I was able to reproduce the issue. 

In [9]: shared.devices
Out[9]: {'chimes': [], 'doorbells': []}

Maybe when the account is shared, we will need have a new flag to allow it searching true history. I'm investigating this issue.

**Comment by tchellomello** [comment]
Guys, cool I think we  figured it out. The issue was that a shared device uses another key on the JSON dictionary and for that reason the doorbell was returning `None`. 

I've started the PR https://github.com/tchellomello/python-ring-doorbell/pull/32 that has the fix, however keep in mind that only the doorbell are possible to be shared. I could not see a chime via the shared account. Am I right on this? Are you able to see a share chime or only the doorbell? 

@GreenTurtwig  could you try to run that code to see if works for you?

**Comment by tchellomello** [comment]
Fixed by PR #32

**Comment by GreenTurtwig** [comment]
Sorry about the late reply, I was rather busy.  
But it all seems to work fine!
![screenshot_2017-03-21_18-22-45](https://cloud.githubusercontent.com/assets/15905797/24163798/7e50dbd2-0e63-11e7-85a4-cf2734e6ac6d.png)
Thanks for "fixing" this so quickly, just got to wait for HA to have the updared PIP package. :cat2:

**Comment by tchellomello** [comment]
I'm working on this
