### ISSUE TITLE
Can't install with [listen] option

### ISSUE THREAD

**Issue by JPAssoc** [tchellomello/python-ring-doorbell#325]
Hi,

If I try to install the latest release with the [latest] option, I get this error message:

ring-doorbell 0.7.3 does not provide the extra 'listen'

Any idea how I get round this as I really need to make use of the listening part of the API?

Many thanks,

Jon

**Comment by cudmore** [comment]
If your using a zsh shell (macOS) then you need quotes ('') like

pip install 'ring_doorbell[listen]'

**Comment by JPAssoc** [comment]
Many thanks for that. I'm actually installing it on Raspberry Pi. I've tried using the quotes, but that doesn't seem to help, as it's still claiming that "ring-doorbell 0.7.3 does not provide the extra 'listen'" (see attached screenshot). Everything else seems fine, however - should I assume that it's all OK?
<img width="1091" alt="Screenshot 2024-01-22 at 09 38 37" src="https://github.com/tchellomello/python-ring-doorbell/assets/52919066/1a58cd2f-b93b-4bb5-9822-536f1949fcfe">

**Comment by JPAssoc** [comment]
D'oh. Many thanks - should have thought of that.
