### ISSUE TITLE
policies on pydantic and typing

### ISSUE THREAD

**Issue by fhvilshoj** [tchellomello/python-ring-doorbell#345]
Hi!

Thanks for all the hard work on this repo. I just discovered the project today and dived right in.
While reading some of all the code, I realised that lots of the code is well tested but ill typed.

I read the contribution guidelines but only very little was written about both typing systems and dependencies.

Before I dive into it, how would you feel about PRs on typing out the central parts of the code - starting with data coming from the apis. Since it's already nicely cataloged in the test fixtures, it wouldn't be too big of a lift to type all expected responses with [pydantic](https://pypi.org/project/pydantic/)... of course that requires adding that dependency to the project which I don't know if you like?

I think it would make the code much safer, contributions easier, and arguably ease the cognitive load of code adoption.

Wouldn't it be nice if one knew what a `session` was without having to wait for an api call to actually see it at runtime?

<img width="698" alt="image" src="https://github.com/tchellomello/python-ring-doorbell/assets/9026202/6b3c86d3-0625-474d-9e8c-a1f394185ade">

LMK what you think 🤙

**Comment by sdb9696** [comment]
We’d welcome some PR contributions for typing but I think general python type hints are required before we start going down the pydantic route for api responses etc

Then there is a broader question of how suitable pydantic is, because the breaking api change between v1 and v2 causes problems in HomeAssistant where this library is widely used.

**Comment by sdb9696** [comment]
typing is now sorted, pydantic question is unresolved but closing for now.
