### ISSUE TITLE
Can't import RingEventListener

### ISSUE THREAD

**Issue by JPAssoc** [tchellomello/python-ring-doorbell#353]
I've upgraded to Python 3.9 and installed the [listen] version of the doorbell package, but I'm still not able to import the required class. Here are the first few lines of my code:

#!/usr/bin/env python

import sys

print("Here we go, version is ", sys.version_info)

import json
import getpass
import time
import asyncio
import struct
import RPi.GPIO as GPIO
import logging
from pathlib import Path
from pprint import pprint
from ring_doorbell import Ring, Auth
from ring_doorbell.exceptions import RingError
from oauthlib.oauth2 import MissingTokenError
from ring_doorbell.const import DINGS_ENDPOINT
from ring_doorbell.listen import can_listen

if can_listen:
	print("Can listen")
else:
	print("Can't listen")

from ring_doorbell.listen import RingEventListener

This is what I see in my Raspberry Pi terminal:

<img width="833" alt="Screenshot 2024-03-13 at 13 45 34" src="https://github.com/tchellomello/python-ring-doorbell/assets/52919066/5c28400e-9a6b-47c6-934c-6f19eb590274">

It's probably something really stupid that I'm doing, but I can't see it at the moment, and any help would be appreciated.

Jon

**Comment by sdb9696** [comment]
It looks like the `listen` extra has not installed. What do you see when you run `pip freeze | grep firebase-messaging`?  You should see `firebase-messaging==0.2.0`.

Try to install again with `pip install ring-doorbell[listen]==0.8.7` and look at the output to see if `firebase-messaging` is getting installed.

**Comment by JPAssoc** [comment]
Thanks for the quick response. I think it's installed already:

<img width="1252" alt="Screenshot 2024-03-13 at 14 27 23" src="https://github.com/tchellomello/python-ring-doorbell/assets/52919066/febf224f-051a-4846-a3ed-25a1ee24a8e0">

**Comment by JPAssoc** [comment]
OK, I'll try that. Thanks.

**Comment by sdb9696** [comment]
Hi, did this work in a virtual env?

**Comment by JPAssoc** [comment]
Sorry - got diverted to other stuff, so haven't yet had time to try this. Will let you know!

**Comment by JPAssoc** [comment]
Hi, finally got round to reinstalling the OS and upgrading Python and it now installs correctly. However, I'm struggling a bit with using it for getting asynchronous notifications of events. Here's a snippet of my code:


#!/usr/bin/env python

import sys
import json
import getpass
import time
import asyncio
import struct
import logging
from pathlib import Path
from pprint import pprint
from ring_doorbell import Ring, Auth, AuthenticationError, Requires2FAError
from ring_doorbell.exceptions import RingError
from ring_doorbell.const import DINGS_ENDPOINT
from ring_doorbell.listen import can_listen

from ring_doorbell.listen import RingEventListener

class myListener:
	def ringCB(self):
#		logging.info('Device: %s, kind %s' %s(event.device_name, event.device_kind))
		logging.info('Ding!')

	async def initialise(self):
		logging.basicConfig(format='%(asctime)s - %(message)s', filename='Ring2ByronServer.log', level=logging.INFO)

#	Login and 2FA stuff removed for clarity

		global ring
		ring = Ring(auth)
		ring.update_data()

		listener = RingEventListener(ring)
		listener.start(self.ringCB())

		if listener.subscribed:
			logging.info('Subscribed')
		else:
			logging.info('Not subscribed')

		if listener.started:
			logging.info('Started')
		else:
			logging.info('Not started')

if __name__ == "__main__":
	asyncio.run(myListener().initialise())


So I basically want ringCB to fire every time there's an event on my Ring network. However, all I see is this:

2024-07-03 15:49:11,343 - Ding!
2024-07-03 15:49:14,910 - Registered with FCM
2024-07-03 15:49:20,694 - Succesfully logged in to MCS endpoint
2024-07-03 15:49:20,772 - Subscribed
2024-07-03 15:49:20,773 - Started

I'm sure it must be something really stupid that I'm doing, but could you possibly give me some pointers?

Cheers,

Jon

**Comment by JPAssoc** [comment]
And yes, it was something really stupid that I was doing. I'm now getting asynchronous events coming through nicely.
