### ISSUE TITLE
Add support to Stick Up cameras

### ISSUE THREAD

**Issue by tchellomello** [tchellomello/python-ring-doorbell#38]
Would be awesome to have support to Stick Up cameras.  I don't have one but I have plans on buying it to test it. 

If anyone else wants to work on this, please you are very welcome.

**Comment by jlippold** [comment]
FWIW, my floodlight cam doesn't show up using this api.

Maybe the floodlight and stickup cams use the same interface

**Comment by jlippold** [comment]
Ok, I confirmed the flood light is a stick up cam by snooping the /devices endpoint. My python is shitty, but I'll try to submit a pull.

```json
{
    "doorbots": [{
        "id": 00000,
        "description": "Front Door",
        "device_id": "XXX",
        "time_zone": "America/New_York",
        "subscribed": true,
        "subscribed_motions": true,
        "battery_life": 4026,
        "external_connection": false,
        "firmware_version": "1.4.30",
        "kind": "lpd_v1",
        "latitude": 0.00,
        "longitude": 0.00,
        "address": "XXX",
        "settings": {... },
        "features": {
            "motions_enabled": true,
            "show_recordings": true,
            "advanced_motion_enabled": false,
            "people_only_enabled": false,
            "shadow_correction_enabled": false,
            "motion_message_enabled": false
        },
        "owned": true,
        "alerts": {
            "connection": "online"
        },
        "motion_snooze": null,
        "owner": {...}
    }],
    "stickup_cams": [{
        "id": 00000,
        "description": "Driveway",
        "device_id": "XXX",
        "time_zone": "America/New_York",
        "subscribed": true,
        "subscribed_motions": true,
        "battery_life": "92",
        "external_connection": false,
        "firmware_version": "1.6.89",
        "kind": "hp_cam_v1",
        "latitude": 0.0,
        "longitude": 0.0,
        "address": "XXX",
        "settings": {...},
        "features": {
            "motions_enabled": true,
            "show_recordings": true,
            "advanced_motion_enabled": false,
            "people_only_enabled": false,
            "shadow_correction_enabled": false,
            "motion_message_enabled": false
        },
        "owned": true,
        "alerts": {
            "connection": "online"
        },
        "motion_snooze": null,
        "led_status": "off",
        "night_mode_status": "false",
        "ring_cam_light_installed": null,
        "siren_status": {
            "seconds_remaining": 0
        },
        "owner": {...}
    }],    
    "authorized_doorbots": [],
    "chimes": []
}
```

**Comment by tchellomello** [comment]
Awesome!! Your contribution will be very welcome!

**Comment by jlippold** [comment]
https://github.com/tchellomello/python-ring-doorbell/pull/44

Its not great because it doesn't support lights or sirens on the floodlight, but I can access the saved videos.

**Comment by jlippold** [comment]
Also, I built a kodi addon based on your library: https://github.com/jlippold/repository.jlippold/tree/master/plugin.video.ring_doorbell

**Comment by zzsmith** [comment]
Turning floodlights on/off (PUT w/no data)

https://api.ring.com/clients_api/doorbots/{account_id}/floodlight_light_on?api_version=9&auth_token={auth_token}

https://api.ring.com/clients_api/doorbots/{account_id}/floodlight_light_off?api_version=9&auth_token={auth_token}

**Comment by jlippold** [comment]
@zzsmith I can't get that PUT for floodlights to work, tried it in multiple ways. Where'd you get this info?

**Comment by zzsmith** [comment]
Ended up installing the android developer studio and using "charles proxy" to intercept the https requests generated by the ring app.  Need to use Marshmellow android firmware in the emulator though, the newer ones are more stringent on SSL.

I just checked it again and it looks like the same request:
https://api.ring.com/clients_api/doorbots/{id}/floodlight_light_on?api_version=9&auth_token={auth}

**Comment by jlippold** [comment]
maybe it's not `PUT`? I keep trying combo's and failing

**Comment by jlippold** [comment]
Ugh it works fine, sorry @zzsmith ... the node js library i was using sent a silly hardware id https://github.com/davglass/doorbot/blob/master/doorbot.js#L141 that broke everything

**Comment by subnetangel** [comment]
I also have a Ring Floodlight that I would like to test. Looks like you guys got this going, I am pretty new to Python so not sure how to test it directly. @tchellomello I would use this via homeassistant any tips on testing this?

**Comment by jsetton** [comment]
@subnetangel I just submitted a PR to add support for the floodlight lights and siren. Would you be willing to test the control of the siren? That's the only part I couldn't test properly without disturbing my neighbors.

You can test the changes I made using my forked repository:
`pip install git+https://github.com/jsetton/python-ring-doorbell`

To test the siren:
```python
import time
from ring_doorbell import Ring
myring = Ring('foo@bar', 'secret')
 
for dev in list(myring.stickup_cams):
    # turn on siren for 5 seconds
    dev.siren = 5
    time.sleep(10)
    # turn on siren for 10 seconds but force it to turn off after 5
    dev.siren = 10
    time.sleep(5)
    dev.siren = 0
```

**Comment by subnetangel** [comment]
@jsetton It works!!!

**Comment by tchellomello** [comment]
Awesome guys!! Thanks for your contribution @jsetton and for testing @subnetangel. 
I don't have a stick up camera or a floodlight, but since you guys tested and I'm going to merge it and publish a new package on pypi so then you can submit your PR to HA as well. 

Good teamwork guys!! 

Thanks!!

**Comment by darkstar939** [comment]
siren works great, what is the command for floodlight?

**Comment by darkstar939** [comment]
disregard I wrote my own script using the api calls @zzsmith posted

**Comment by el3359** [comment]
Hello

Anybody know the URI for activated motion notification on the RING App?

Regards

**Comment by 242Racing** [comment]
I would also like to have the URI for activate/deactivate "Motion alerts".

**Comment by jsetton** [comment]
Based on my understanding, there is no direct way to activate/deactivate motion alerts. However, you could achieve that by activating/deactivating any of the motion zones (#110).

**Comment by jsetton** [comment]
I spoke too soon 😄 I guess I rely too much on motion schedules to realize that you can simply manually enable/disable motion alerts.

Anyway, I just opened a new request (#125) including the URI to accomplish this.

**Comment by JaniniRami07** [comment]
Here I have written this code for ring doorbells and stick up cameras and if you want to use it for doorbells just replace stickup_cams with doorbells:
https://github.com/JaniniRami07/PyRing
