### ISSUE TITLE
AttributeError: 'Ring' object has no attribute 'has_subscription'

### ISSUE THREAD

**Issue by cemeyer2** [tchellomello/python-ring-doorbell#40]
Using the code in the readme:

```
from ring_doorbell import Ring

myring = Ring('user@example.com', 'secret')

print myring.has_subscription
```
I receive the following error: `AttributeError: 'Ring' object has no attribute 'has_subscription'`

**Comment by tchellomello** [comment]
@cemeyer2  Thanks for reporting this issue.

The parameter `has_subscription` has been dropped on this newer version. 

I'll submit a PR to remove it from the docs.
