### ISSUE TITLE
Feature Request: adjust mechanical chime setting

### ISSUE THREAD

**Issue by superm1** [tchellomello/python-ring-doorbell#43]
I'm using this library through home-assistant right now for motion and ding detection.  I've set up rules that allow turning on lights when motion is found by Ring with the right conditions.

What I'd really like is the ability to turn on/off the mechanical doorbell connected to my Ring so I can make rules associated with that.  
There's a setting in the Android app that lets you do this, but it's buried in a few menus.

**Comment by tchellomello** [comment]
Hello @superm1, thanks for your message. 

That is already possible. Check this code https://github.com/tchellomello/python-ring-doorbell/blob/dev/ring_doorbell/__init__.py#L489-L508

Please give a try and let me know if that worked for you.

**Comment by superm1** [comment]
@tchellomello oh thanks!  I had assumed the problem was this library not in HA, but it seems that HA hadn't bubbled it up.  I'll give it a shot with the library by hand and file an issue with that plugin @HA.

**Comment by tchellomello** [comment]
@superm1  sounds good. I'm closing this issue for now.
