### ISSUE TITLE
How to get RSSI?

### ISSUE THREAD

**Issue by keeth** [tchellomello/python-ring-doorbell#47]
This module is great thank you! I am using it to monitor the health of my doorbell with MRTG :)

I see the battery level is there but I don't see the RSSI which the app shows me.  Anyone know how to get that?

I followed the link to the post about reverse-engineering the protocol but that page is 404 now unfortunately.

Thanks!

**Comment by zzsmith** [comment]
GET	https://api.ring.com/clients_api/doorbots/{deviceid}/health?api_version=9&auth_token={auth_token}

JSON Response:
{
	"device_health": {
		"id": 123456,
		"wifi_name": "ssid",
		"battery_percentage": 100,
		"battery_percentage_category": "very_good",
		"battery_voltage": null,
		"battery_voltage_category": null,
		"latest_signal_strength": -37,
		"latest_signal_category": "good",
		"average_signal_strength": -37,
		"average_signal_category": "good",
		"firmware": "1.9.3",
		"firmware_out_of_date": false,
		"updated_at": "2017-09-20T00:00:00Z",
		"wifi_is_ring_network": false
	}
}

**Comment by tchellomello** [comment]
Nice... let's implement this!

**Comment by tchellomello** [comment]
@zzsmith  Thanks for posting the URL. Do you happen to know the URL for the chimes?

**Comment by zzsmith** [comment]
Don't have a chime pro but normal chime is:

GET https://api.ring.com/clients_api/chimes/{id}/linked_doorbots?api_version=9&auth_token={authtoken}

{
	"linked_doorbots": [{
		"id": 1234,
		"description": "Cam1",
		"device_id": "5678",
		"kind": "hp_cam_v1",
		"call_alerts": false,
		"motion_alerts": false,
		"owner": {
			"id": 1111,
			"first_name": "bob",
			"last_name": "bob",
			"email": "bob@google.com"
		}
	}, {
		"id": 1234,
		"description": "Doorcam",
		"device_id": "8765",
		"kind": "lpd_v2",
		"call_alerts": true,
		"motion_alerts": false,
		"owner": {
			"id": 1111,
			"first_name": "bob",
			"last_name": "bob",
			"email": "bob@google.com"
		}
	}]
}

GET https://api.ring.com/clients_api/chimes/{id}/health?api_version=9&auth_token={authtoken}

{
	"device_health": {
		"id": 1234,
		"wifi_name": "ssid",
		"battery_percentage": 100,
		"battery_percentage_category": null,
		"battery_voltage": null,
		"battery_voltage_category": null,
		"latest_signal_strength": -33,
		"latest_signal_category": "good",
		"average_signal_strength": -33,
		"average_signal_category": "good",
		"firmware": "1.2.3",
		"firmware_out_of_date": false,
		"updated_at": "2017-09-22T00:00:00Z",
		"wifi_is_ring_network": false
	}
}

GET https://api.ring.com/clients_api/ringtones?api_version=9&auth_token={authtoken}

{
	"default_ding_user_id": "ring",
	"default_ding_id": "00053e86-c08f-4aad-a500-84a51355433d",
	"default_motion_user_id": "ring",
	"default_motion_id": "00053e86-f43b-738f-7287-5693688ec52b",
	"audios": [{
		"user_id": "ring",
		"id": "00053e86-c08f-4aad-a500-84a51355433d",
		"description": "Ring Default",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053e86-c08f-4aad-a500-84a51355433d.wav",
		"checksum": 27149358,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053e86-f43b-738f-7287-5693688ec52b",
		"description": "Default Motion",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053e86-f43b-738f-7287-5693688ec52b.wav",
		"checksum": 25273352,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053f55-e161-460d-fba3-20566a5910fe",
		"description": "Bats",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053f55-e161-460d-fba3-20566a5910fe.wav",
		"checksum": 54767122
	}, {
		"user_id": "ring",
		"id": "00053f55-e2e8-eddb-16c4-908f53f4fa95",
		"description": "Bats",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053f55-e2e8-eddb-16c4-908f53f4fa95.wav",
		"checksum": 54767122
	}, {
		"user_id": "ring",
		"id": "00053f56-0027-7594-7287-5693688ec52b",
		"description": "Ghosts",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053f56-0027-7594-7287-5693688ec52b.wav",
		"checksum": 58257656
	}, {
		"user_id": "ring",
		"id": "00053f56-00e4-aef8-7287-5693688ec52b",
		"description": "Ghosts",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053f56-00e4-aef8-7287-5693688ec52b.wav",
		"checksum": 58257656
	}, {
		"user_id": "ring",
		"id": "00053f56-02da-82fd-fba3-20566a5910fe",
		"description": "Howl",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053f56-02da-82fd-fba3-20566a5910fe.wav",
		"checksum": 40427768
	}, {
		"user_id": "ring",
		"id": "00053f56-035e-9640-7287-5693688ec52b",
		"description": "Howl",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053f56-035e-9640-7287-5693688ec52b.wav",
		"checksum": 40427768
	}, {
		"user_id": "ring",
		"id": "00053fa0-6978-fefb-04a6-bf03047343d3",
		"description": "Scream",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053fa0-6978-fefb-04a6-bf03047343d3.wav",
		"checksum": 34820952
	}, {
		"user_id": "ring",
		"id": "00053fa0-6a2a-6d21-fba3-20566a5910fe",
		"description": "Scream",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053fa0-6a2a-6d21-fba3-20566a5910fe.wav",
		"checksum": 34820952
	}, {
		"user_id": "ring",
		"id": "00053fa0-7277-3024-16c4-908f53f4fa95",
		"description": "Spooky Organs",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053fa0-7277-3024-16c4-908f53f4fa95.wav",
		"checksum": 46679635
	}, {
		"user_id": "ring",
		"id": "00053fa0-72fe-9d56-7287-5693688ec52b",
		"description": "Spooky Organs",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053fa0-72fe-9d56-7287-5693688ec52b.wav",
		"checksum": 46679635
	}, {
		"user_id": "ring",
		"id": "00053fa0-871b-9b09-fba3-20566a5910fe",
		"description": "Witch Cackle",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053fa0-871b-9b09-fba3-20566a5910fe.wav",
		"checksum": 34247396
	}, {
		"user_id": "ring",
		"id": "00053fa0-879f-29e4-5af2-5646cb2449be",
		"description": "Witch Cackle",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053fa0-879f-29e4-5af2-5646cb2449be.wav",
		"checksum": 34247396
	}, {
		"user_id": "ring",
		"id": "00053fa0-9b4e-25e6-6665-70eb8eb2b101",
		"description": "Creepy Laugh",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053fa0-9b4e-25e6-6665-70eb8eb2b101.wav",
		"checksum": 54635895
	}, {
		"user_id": "ring",
		"id": "00053fa0-9c53-2d06-5af2-5646cb2449be",
		"description": "Creepy Laugh",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053fa0-9c53-2d06-5af2-5646cb2449be.wav",
		"checksum": 54635895
	}, {
		"user_id": "ring",
		"id": "00053fa0-ade4-6bc6-7730-249c40dbbf59",
		"description": "Screeching Cat",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053fa0-ade4-6bc6-7730-249c40dbbf59.wav",
		"checksum": 17456907
	}, {
		"user_id": "ring",
		"id": "00053fa0-af43-1cef-7730-249c40dbbf59",
		"description": "Screeching Cat",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053fa0-af43-1cef-7730-249c40dbbf59.wav",
		"checksum": 17456907
	}, {
		"user_id": "ring",
		"id": "00053fa0-b59d-8a65-7287-5693688ec52b",
		"description": "Creaking Door",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053fa0-b59d-8a65-7287-5693688ec52b.wav",
		"checksum": 43464257
	}, {
		"user_id": "ring",
		"id": "00053fa0-b62c-f0ad-6665-70eb8eb2b101",
		"description": "Creaking Door",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053fa0-b62c-f0ad-6665-70eb8eb2b101.wav",
		"checksum": 43464257
	}, {
		"user_id": "ring",
		"id": "00053fa2-8f22-ca27-7730-249c40dbbf59",
		"description": "Ring Alert 2",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053fa2-8f22-ca27-7730-249c40dbbf59.wav",
		"checksum": 38105324,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa2-8fc4-7511-fba3-20566a5910fe",
		"description": "Ring Alert 2",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053fa2-8fc4-7511-fba3-20566a5910fe.wav",
		"checksum": 38105324,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa2-92ff-3c7a-7730-249c40dbbf59",
		"description": "Ring Alert 3",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053fa2-92ff-3c7a-7730-249c40dbbf59.wav",
		"checksum": 50376770,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa2-93c6-516c-16c4-908f53f4fa95",
		"description": "Ring Alert 3",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053fa2-93c6-516c-16c4-908f53f4fa95.wav",
		"checksum": 50376770,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa2-a310-caca-16c4-908f53f4fa95",
		"description": "Harp",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053fa2-a310-caca-16c4-908f53f4fa95.wav",
		"checksum": 32423613,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa2-a387-24cc-6665-70eb8eb2b101",
		"description": "Harp",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053fa2-a387-24cc-6665-70eb8eb2b101.wav",
		"checksum": 32423613,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa2-a654-ad6b-5af2-5646cb2449be",
		"description": "Flashback",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053fa2-a654-ad6b-5af2-5646cb2449be.wav",
		"checksum": 30511500,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa2-a6dc-bb8e-fba3-20566a5910fe",
		"description": "Flashback",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053fa2-a6dc-bb8e-fba3-20566a5910fe.wav",
		"checksum": 30511500,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa2-a83d-e5a4-5af2-5646cb2449be",
		"description": "Ding-Dong",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053fa2-a83d-e5a4-5af2-5646cb2449be.wav",
		"checksum": 34569291,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa2-a8aa-f881-16c4-908f53f4fa95",
		"description": "Ding-Dong",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053fa2-a8aa-f881-16c4-908f53f4fa95.wav",
		"checksum": 34569291,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa2-adc1-44c6-7287-5693688ec52b",
		"description": "Triangle",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053fa2-adc1-44c6-7287-5693688ec52b.wav",
		"checksum": 49317951,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa2-ae2f-a791-fba3-20566a5910fe",
		"description": "Triangle",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053fa2-ae2f-a791-fba3-20566a5910fe.wav",
		"checksum": 49317951,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa2-af83-6b62-6665-70eb8eb2b101",
		"description": "Upbeat",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053fa2-af83-6b62-6665-70eb8eb2b101.wav",
		"checksum": 25943707,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa2-e870-ee29-7287-5693688ec52b",
		"description": "Navi",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053fa2-e870-ee29-7287-5693688ec52b.wav",
		"checksum": 11164301,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa2-e8d1-ac6d-16c4-908f53f4fa95",
		"description": "Navi",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053fa2-e8d1-ac6d-16c4-908f53f4fa95.wav",
		"checksum": 11164301,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa3-1e4c-b42d-fba3-20566a5910fe",
		"description": "Xylophone",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053fa3-1e4c-b42d-fba3-20566a5910fe.wav",
		"checksum": 65153984,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa3-1eb3-eb40-fba3-20566a5910fe",
		"description": "Xylophone",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053fa3-1eb3-eb40-fba3-20566a5910fe.wav",
		"checksum": 65153984,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa3-22b0-33bb-7287-5693688ec52b",
		"description": "Train Whistle",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053fa3-22b0-33bb-7287-5693688ec52b.wav",
		"checksum": 15947918,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa3-233f-4080-6665-70eb8eb2b101",
		"description": "Train Whistle",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053fa3-233f-4080-6665-70eb8eb2b101.wav",
		"checksum": 15947918,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa3-246f-7590-6665-70eb8eb2b101",
		"description": "Charge!",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053fa3-246f-7590-6665-70eb8eb2b101.wav",
		"checksum": 21722522,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa3-24e2-6bea-6665-70eb8eb2b101",
		"description": "Charge!",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053fa3-24e2-6bea-6665-70eb8eb2b101.wav",
		"checksum": 21722522,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa3-2657-fece-7287-5693688ec52b",
		"description": "Dogs Barking",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00053fa3-2657-fece-7287-5693688ec52b.wav",
		"checksum": 29085781,
		"available": true
	}, {
		"user_id": "ring",
		"id": "00053fa3-26e6-2248-16c4-908f53f4fa95",
		"description": "Dogs Barking",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00053fa3-26e6-2248-16c4-908f53f4fa95.wav",
		"checksum": 29085781,
		"available": true
	}, {
		"user_id": "ring",
		"id": "0005410f-8df3-ff6a-04a6-bf03047343d3",
		"description": "\"Motion Detected\"",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/0005410f-8df3-ff6a-04a6-bf03047343d3.wav",
		"checksum": 6687724
	}, {
		"user_id": "ring",
		"id": "000541c2-05ec-d432-a500-84a51355433d",
		"description": "Turkey Gobble",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/000541c2-05ec-d432-a500-84a51355433d.wav",
		"checksum": 9329115
	}, {
		"user_id": "ring",
		"id": "000541c3-ece8-e661-fba3-20566a5910fe",
		"description": "Upbeat",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/000541c3-ece8-e661-fba3-20566a5910fe.wav",
		"checksum": 25943707,
		"available": true
	}, {
		"user_id": "ring",
		"id": "000541d4-2eb0-69e0-a500-84a51355433d",
		"description": "Turkey Gobble",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/000541d4-2eb0-69e0-a500-84a51355433d.wav",
		"checksum": 25239373
	}, {
		"user_id": "ring",
		"id": "000541e9-b5fa-a3e6-6665-70eb8eb2b101",
		"description": "Turkey Gobble",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/000541e9-b5fa-a3e6-6665-70eb8eb2b101.wav",
		"checksum": 25239373
	}, {
		"user_id": "ring",
		"id": "0005437c-2503-8609-1796-fe5ea487eda0",
		"description": "Deck the Halls",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/0005437c-2503-8609-1796-fe5ea487eda0.wav",
		"checksum": 50709763
	}, {
		"user_id": "ring",
		"id": "0005437c-256c-f08b-15ed-c60763a7f4ab",
		"description": "Deck the Halls",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/0005437c-256c-f08b-15ed-c60763a7f4ab.wav",
		"checksum": 50709763
	}, {
		"user_id": "ring",
		"id": "0005437f-3cf7-a7c3-e10e-fb07dbef630b",
		"description": "Deck the Halls",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/0005437f-3cf7-a7c3-e10e-fb07dbef630b.wav",
		"checksum": 50709763
	}, {
		"user_id": "ring",
		"id": "00054390-00ee-29e7-1796-fe5ea487eda0",
		"description": "Ho Ho Ho!",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00054390-00ee-29e7-1796-fe5ea487eda0.wav",
		"checksum": 47334104
	}, {
		"user_id": "ring",
		"id": "00054390-022f-f0de-2acf-96d62cc32629",
		"description": "Ho Ho Ho!",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00054390-022f-f0de-2acf-96d62cc32629.wav",
		"checksum": 47334104
	}, {
		"user_id": "ring",
		"id": "00054390-0343-420b-15ed-c60763a7f4ab",
		"description": "Jingle Bells",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00054390-0343-420b-15ed-c60763a7f4ab.wav",
		"checksum": 54011599
	}, {
		"user_id": "ring",
		"id": "00054390-053f-9b08-15ed-c60763a7f4ab",
		"description": "Jingle Bells",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00054390-053f-9b08-15ed-c60763a7f4ab.wav",
		"checksum": 54011599
	}, {
		"user_id": "ring",
		"id": "00054390-066c-c65d-cef4-b63b70e927d1",
		"description": "Sleigh Bells",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00054390-066c-c65d-cef4-b63b70e927d1.wav",
		"checksum": 35612289
	}, {
		"user_id": "ring",
		"id": "00054390-0729-e61a-06f1-384e5ea598f9",
		"description": "Sleigh Bells",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00054390-0729-e61a-06f1-384e5ea598f9.wav",
		"checksum": 35612289
	}, {
		"user_id": "ring",
		"id": "00054391-30e2-eb60-ef30-531ebbd19949",
		"description": "Dreidel Dreidel",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/00054391-30e2-eb60-ef30-531ebbd19949.wav",
		"checksum": 58814224
	}, {
		"user_id": "ring",
		"id": "00054391-323e-d285-2acf-96d62cc32629",
		"description": "Dreidel Dreidel",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/00054391-323e-d285-2acf-96d62cc32629.wav",
		"checksum": 58814224
	}, {
		"user_id": "ring",
		"id": "0005480d-6799-958d-e088-c0f7715367a3",
		"description": "Doorbot",
		"kind": "ding",
		"url": "https://ringtones.ring.com/ring/ding/0005480d-6799-958d-e088-c0f7715367a3.wav",
		"checksum": 21400380,
		"available": true
	}, {
		"user_id": "ring",
		"id": "0005480d-6d7d-ad90-a0b3-625e17d992ba",
		"description": "Doorbot",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/0005480d-6d7d-ad90-a0b3-625e17d992ba.wav",
		"checksum": 21400380
	}, {
		"user_id": "ring",
		"id": "0005480d-6d97-b3ce-a0b3-625e17d992ba",
		"description": "Doorbot",
		"kind": "motion",
		"url": "https://ringtones.ring.com/ring/motion/0005480d-6d97-b3ce-a0b3-625e17d992ba.wav",
		"checksum": 21400380,
		"available": true
	}]
}

POST https://api.ring.com/clients_api/chimes/{id}/play_sound?api_version=9&auth_token={auth_token}&kind=ding

**Comment by tchellomello** [comment]
Great info @zzsmith  Thank you!

**Comment by tchellomello** [comment]
@zzsmith do you happen to have a stickup cam to know which URL is used to get the health information?

**Comment by zzsmith** [comment]
Don't have a stickup cam but here is for the floodlight which might be the same:

GET https://api.ring.com/clients_api/doorbots/{id}/health?api_version=9&auth_token={auth_token}

**Comment by tchellomello** [comment]
@zzsmith @keeth  guys, functionality implemented. I'll publish a new version tomorrow since I want to fix one more bug to the newer version. 
Thank you for your assistance!!
