### ISSUE TITLE
Push Notification Token

### ISSUE THREAD

**Issue by NicolaRusso** [tchellomello/python-ring-doorbell#61]
Hi!
I'm not sure the push notification token works.. I've tried to put an url (a servlet) and I got 204 after the PUT request. However I don't receive any call to my servlet when the doorbot is ringing.

Am I missing something?

Thanks

**Comment by NicolaRusso** [comment]
Here the request made after getting token:

PUT /clients_api/device HTTP/1.1
Host: api.ring.com
User-Agent: Dalvik/1.6.0 (Linux; Android 4.4.4; Build/KTU84Q)
Accept-Encoding: gzip, deflate
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded

api_version=9&device%5Bmetadata%5D%5Bdevice_model%5D=KWM&device%5Bmetadata%5D%5Bdevice_name%5D=Python&device%5Bmetadata%5D%5Bresolution%5D=600x800&device%5Bmetadata%5D%5Bapp_version%5D=1.3.806&device%5Bmetadata%5D%5Bapp_instalation_date%5D=&device%5Bmetadata%5D%5Bmanufacturer%5D=Qemu&device%5Bmetadata%5D%5Bdevice_type%5D=desktop&device%5Bmetadata%5D%5Barchitecture%5D=x86&device%5Bmetadata%5D%5Blanguage%5D=en&auth_token=TOKEN_HIDDEN&device%5Bpush_notification_token%5D=https%3A%2F%2Fmyurl.com

**Comment by tchellomello** [comment]
@NicolaRusso  the current support to push tokens are not 100% functional and they need some work. 

They are because during the initial study when reversing engineering it was part of the headers, but we never really put it into use.

**Comment by tchellomello** [comment]
Closing it for now
