### ISSUE TITLE
fix my Python ignorance

### ISSUE THREAD

**Issue by stephenmhall** [tchellomello/python-ring-doorbell#62]
I thought I was pretty oh-fey on Python matters but I cannot work out how to poll the Ring service for an activation. I have compared your code with the php original and it has a poll() function where you have a check_alerts() function but I can get nothing back. I have got the other parts of your code working and ended up with this test code.

seems the insert code doesn't like python.

`
from ring_doorbell import Ring
from time import sleep

myring = Ring('myaccount', 'password')
print (myring.is_connected)

print (myring.devices)

for doorbell in myring.doorbells:
    print (doorbell.wifi_signal_strength)
    print (doorbell.battery_life)
    print (doorbell.firmware)
    
    for event in doorbell.history(limit=15):
        print('ID:       %s' % event['id'])
        print('Kind:     %s' % event['kind'])
        print('Answered: %s' % event['answered'])
        print('When:     %s' % event['created_at'])
        print('--' * 50)
        
    events = doorbell.history(kind='ding')
    print (events)
    
for chime in myring.chimes:
    print(chime.battery_life)
    
print(doorbell.recording_url(doorbell.last_recording_id))

while(1):
    print ("scanning")
    data = doorbell.check_alerts()
    print (data)
    sleep(5)
`

But just get none when trying the doorbell.

Could you post a snippet for polling the service please I'm going daft.

**Comment by tchellomello** [comment]
@stephenmhall thanks for your post. I'm going to give a try tomorrow and I'll let you now.

**Comment by dbrand666** [comment]
The simple answer is change the sleep(5) to sleep(30) (you may find a smaller value but not smaller enough). There seems to be some caching and rate limiting going on. If you keep polling (try history(), eg) you'll keep getting the cached result. You need to sleep for a while before a request will get updated data.

I was hoping I'd be able to poll the status in something near enough to realtime and ran into this same problem. We need to look into how the notification system in the app works.

**Comment by tchellomello** [comment]
@dbrand666  yes, that is a good point. We need to look into the subscriber and study a way to get updates from it.

**Comment by stephenmhall** [comment]
Here is a question for any Android developers who might be reading, if we install the ring app on the virtual Android phone within Android Studio can you monitor the internal communications flowing round the phone? Or are the apps sandboxed and you can only monitor apps you create? I would suspect that the ring back end is pushing out activations to your account rather than all the devices you have it installed on polling the service fast enough to make it look nearly real time.

**Comment by dbrand666** [comment]
I took a look at the Android app's communication with ring.com. Sorry to say that all it's doing is polling the https://api.ring.com/clients_api/dings/active?api_version=9 endpoint every 10 seconds. This is not what I was hoping to see.

So @stephenmhall, just increase the sleep to 10 seconds and it should work for you too.

This also explains why it takes so long for the Ring app to respond to an event.

**Comment by stephenmhall** [comment]
Pretty disappointing that it all works on polling and not a push service.

**Comment by tchellomello** [comment]
Closing as the questions has been addressed.
