### ISSUE TITLE
Doorbell history does not return all events

### ISSUE THREAD

**Issue by troopermax** [tchellomello/python-ring-doorbell#63]
When going through the history of events on a doorbell, much as in the basic examples, it doesn't seem to get all the events - I'm guessing the request that is being made for these has a hard limit/maximum (I did try setting the limit parameter to be really high), and it will probably take multiple requests to truly get all the events. Not sure what additional parameters to the URL will be necessary to select the earlier events, but I know when browsing my events on the Ring website it allows me to scroll back to my earliest events. Useful API otherwise, great work!

**Comment by tchellomello** [comment]
@troopermax  thank you for your post. Could you please provide a code snippet on how are you trying to get the history?

**Comment by troopermax** [comment]
Pretty much following the basic instructions for the most part:

> # Installing from PyPi
> $ pip install ring_doorbell

> Initializing your Ring object
> 
> from ring_doorbell import Ring
> myring = Ring('foo@bar', 'secret')
> 
> myring.is_connected
> True

That part all checked out

```
doorbell = myring.doorbells[0]
>>> len(doorbell.history())
30
>>> len(doorbell.history(100))
100
>>> len(doorbell.history(101))
100
```
Yet I do have more than 100 events - when browsing them on the Ring website, I have to scroll down to trigger it to load more events. The app behaves similarly. So I'm guessing there are additional parameters used to select different sets of events, but I don't know that I'll be able to take a closer look to figure out what they are any time soon or I would love to help.

**Comment by troopermax** [comment]
Ripping a bit from the Ring code and your code, I was able to download all my history with this script:

```
from ring_doorbell import Ring
myring = Ring('foo@bar', 'secret')

print "Connected: "+str(myring.is_connected)
doorbell = myring.doorbells[0]

from ring_doorbell.const import (
    API_URI, DOORBELLS_ENDPOINT, DOORBELL_VOL_MIN, DOORBELL_VOL_MAX,
    DOORBELL_EXISTING_TYPE, DINGS_ENDPOINT, FILE_EXISTS,
    LIVE_STREAMING_ENDPOINT, MSG_BOOLEAN_REQUIRED, MSG_EXISTING_TYPE,
    MSG_VOL_OUTBOUND, URL_DOORBELL_HISTORY, URL_RECORDING)

history=doorbell._ring.query(API_URI + URL_DOORBELL_HISTORY.format(doorbell.account_id), extra_params={'limit':'1000'})

while(len(history) > 0):
	for event in doorbell.history():
		file=str(event['created_at'])+'_'+str(event['kind'])+'_'+str(event['answered'])+'_'+str(event['id'])
		file=file.replace(' ','_').replace(':','.')+'.mp4'
		print file
		doorbell.recording_download(event['id'],filename=file,override=False)
	# Grab more history and continue
	history=doorbell._ring.query(API_URI + URL_DOORBELL_HISTORY.format(doorbell.account_id), extra_params={'older_than':history[-1]['id']})
```
'older_than' is the key parameter here, and I was just giving it the id of the last history event fetched to get more - I'll leave it up to you if/how you want to incorporate this into your API.

**Comment by tchellomello** [comment]
@troopermax  that looks good. I'll incorporate that into the library and create a session for scripts and place your script there. 

I'll work on this tonight!

Thanks!!
