### ISSUE TITLE
Using WebHooks for check_alerts()?

### ISSUE THREAD

**Issue by markuzzi** [tchellomello/python-ring-doorbell#80]
Hi,

I was not sure from looking at the code. I think check_alerts() is polling the ring.com api each time, correct? Is there a mechanism for using web hooks or the like with the ring.com API to decrease traffic?

Best, Markus

**Comment by tchellomello** [comment]
Hello @markuzzi, 
    Thanks for your post.  We already had this discussion on previously issue and nobody found any method or way to get pushed notifications. 
    
     Please if you find a way we would be more than happy to hear about it. 

Thanks!

**Comment by Vitiate** [comment]
It might be easier to setup a traffic sniffer and monitor for events on the local network. I would still like to figure out a way to play the video stream on my webos enabled tv. I can already force the tv to a url.

**Comment by tchellomello** [comment]
Closing this issue for now in favor of #62
