### ISSUE TITLE
Returning more then the first hundred events

### ISSUE THREAD

**Issue by idvorkin** [tchellomello/python-ring-doorbell#84]
I'm using doorbell.history, but it limits to 100 (I'm guessing a ring API issue). Is there a way to apply a paging ability to get more events? 

```python
In [77]: es = [e for e in doorbell.history(limit=115)]
In [78]: len(es)
Out[78]: 100
```

**Comment by tchellomello** [comment]
@idvorkin  yes, that is a limit on the ring's doorbell API, however, you can workaround this issue. 

You can use the doorbell.history(limit=100, older_than=<oldest_object_returned_from_first_limit>). 

``` 
es = [e for e in doorbell.history(limit=100)]
new = [e for e in doorbell.history(limit=100, older_than=es[-1])]
```

That would do the trick. 
See also http://python-ring-doorbell.readthedocs.io/#ring_doorbell.doorbot.RingDoorBell.history

I'm closing this for now.  Please reopen if does not work. 

Thanks.
