### ISSUE TITLE
Configurable polling interval/scheduled update interval

### ISSUE THREAD

**Issue by dooz127** [tchellomello/python-ring-doorbell#85]
Hi Marcello--Thank you so much for putting this package together. It works great but I was wondering if there was a way to configure either the polling interval or the scheduled update interval? My homeassistant log continuously warns me that it's taking longer to update ring than the scheduled update interval of 5 seconds. I get about 30 of these warnings or so for the first two minutes, so it might be the correct behavior but it would still be nice for the polling interval to be configurable. I took a quick peek at const.py to see if it would be straight-forward to do but it looks like it would take more effort that would be beyond my ability. Again, thank you for the package and thank you for the consideration.

**Comment by tchellomello** [comment]
@dooz127 let's file an issue at @homeassistant tracker so then we can enable this feature on the component directly.  Please let me know when you issued this so then we can work together. 
Thanks for your kind words.
