### ISSUE TITLE
[bug] Battery life shows 100 when its not

### ISSUE THREAD

**Issue by mrwhale** [tchellomello/python-ring-doorbell#91]
`Great` API here, been following for a while and now have finally got around to attempting to integrate ring into my homeautomation. I am printing the battery life for a ring doorbell, and using the `battery_life` method its printing 100, however when I dump the Ring doorbell object, it shows the correct battery life within there

```python
>>>from ring_doorbell import Ring
>>>from ring_doorbell import RingDoorBell
>>>from pprint import pprint

>>>myring = Ring('user', 'pass', 'true')

>>>print myring.is_connected
True
>>>obj = RingDoorBell(myring, 'Front Door')
>>>obj.battery_life
100
>>>pprint(vars(obj))
{'_attrs': {u'address': u'myaddress',
            u'alerts': {u'connection': u'online'},
            u'battery_life': u'59',
            u'description': u'Front Door',
<omitted>
'_health_attrs': {u'average_signal_category': u'good',
                   u'average_signal_strength': -49,
                   u'battery_percentage': u'59',
                   u'battery_percentage_category': u'good',
                   u'battery_voltage': None,
                   u'battery_voltage_category': None,
                   u'firmware': u'Up to Date',
                   u'firmware_out_of_date': True,
```

**Comment by mrwhale** [comment]
to add - this shows the correct percentage

```
>>print obj._attrs["battery_life"]
59
```

**Comment by tchellomello** [comment]
Hello @mrwhale, 

  Thanks for reporting this issue. Interesting that I tried to reproduce the same steps you did, but I got different values. 
  
```python
from ring_doorbell import Ring
from pprint import pprint

myring = Ring('username', 'password')
myring.doorbells
[<RingDoorBell: Front Door>]

obj = myring.doorbells[0]
obj.battery_life
100

pprint(vars(obj))
{'_attrs': {'address': 'xxxxxxxxxxxxxx',
            'alerts': {'connection': 'online'},
            'battery_life': 4022,
[...SNIP...]
'_health_attrs': {'average_signal_category': 'okay',
                   'average_signal_strength': -66,
                   'battery_percentage': 4022,
                   'battery_percentage_category': 'unknown',
                   'battery_voltage': 4022,
                   'battery_voltage_category': 'very_good',
```

For the `Ring chimes`, that attribute was already being used https://github.com/tchellomello/python-ring-doorbell/blob/master/ring_doorbell/chime.py#L23-L26

I think I'm getting 4022 because my door bell is connected directly to the power and not to batteries. 

It seems the code is correct but I guess it's the away you are initiailizing the object.  If you look at the code, the `battery_life` attribute is getting exactly the way you posted at `obj._attrs["battery_life"]`. 

https://github.com/tchellomello/python-ring-doorbell/blob/master/ring_doorbell/doorbot.py#L30-L36

What happens if you try instead of initilizating the `RingDoorBell` externally, do use the device auto created by `myring`? Try this:

```python
from ring_doorbell import Ring
from pprint import pprint

myring = Ring('username', 'password')
myring.doorbells
[<RingDoorBell: Front Door>]

obj = myring.doorbells[0]
print(obj.battery_life)
100

print (obj._attrs["battery_life"])

print(obj._health_attrs.get('battery_percentage'))
```

Please let me know. 

Thank you!

**Comment by mrwhale** [comment]
Thanks @tchellomello !

My reasoning behind initialising the RingDoorBell method directly was because I was getting unexpected results from `myring.doorbells` too, but here are the results of that too, still getting `100` for battery life

```python
>>>from ring_doorbell import Ring
>>>from pprint import pprint
>>>myring = Ring('user', 'pass', 'true')
>>>obj = myring.doorbells[0] #Front Door door bell
>>>pprint(vars(obj))
{'_attrs': {u'address': u'address',
            u'alerts': {u'connection': u'online'},
            u'battery_life': u'58',
            u'description': u'Front Door',
....
'_health_attrs': {u'average_signal_category': u'good',
                   u'average_signal_strength': -49,
                   u'battery_percentage': u'58',
                   u'battery_percentage_category': u'good',
                   u'battery_voltage': None,
                   u'battery_voltage_category': None,
                   u'firmware': u'Up to Date',

>>>print(obj.battery_life)
100
>>>print (obj._attrs["battery_life"])
58
>>>print(obj._health_attrs.get('battery_percentage'))
58
```

Anything I can try to help troubleshoot?

**Comment by tchellomello** [comment]
It seems the error is because your attribute is being reported as a string instead of an integer. 

```python
In [1]: a = u'58'

In [2]: a > 100
Out[2]: True
```

To fix, basically let's cast that value: 

```python
In [1]: a = u'58'

In [2]: a > 100
Out[2]: True

In [3]: int(a) > 100
Out[3]: False
```

I'll submit a PR to address this problem.

**Comment by tchellomello** [comment]
@mrwhale  PR created. Could you please check if that fixes the issue?

**Comment by mrwhale** [comment]
seems I commented in the PR instead of here, but this has been solved in ☝️
