### ISSUE TITLE
Check_alerts() function not working

### ISSUE THREAD

**Issue by mrwhale** [tchellomello/python-ring-doorbell#93]
Hopefully I'm just doing it wrong, but the `check_alerts()` function for the doorbell is not working for me

I have set up a ~7s loop, to check that function and get the alert details when one happens

```python
from ring_doorbell import Ring
from ring_doorbell import RingDoorBell
from pprint import pprint
import time

myring = Ring('creds', "False", 'True','http://localhost/', 'True', 'ring_doorbell-session.cache')

while(True):
    obj2 = RingDoorBell(myring, 'Front Door')
    checker = obj2.check_alerts()
    print checker
    print obj2.battery_life
    time.sleep(2)
```

This runs and continues to print `None` and the battery life, after creating a motion event while this loop is running i get nothing

**Comment by asantaga** [comment]
this works for me, but what it does is simply tell u if a Ding or a Motion event was triggered last.. Checkout my code https://github.com/asantaga/alexashowRing/blob/master/alexaringdoor.py

**Comment by mrwhale** [comment]
Thanks @asantaga looks like its just me then! I'll grab that snippet out of your code base there and try that

**Comment by kevnflores** [comment]
@mrwhale you may want to use `return` instead of `print` this may be causing your output to be `none`
